### ISSUE TITLE
FutureWarning when passing numpy array as fixed value to interactive

### ISSUE THREAD

**Issue by tensionhead** [jupyter-widgets/ipywidgets#1718] opened 2017-09-18 19:07 UTC
Hello,

I might have found an odd behavior, when defining an 'interactive' widget and passing one function argument as a fixed numpy array, I get a big red box with the following warning:

*/Users/xxx/anaconda/lib/python3.6/site-packages/traitlets/traitlets.py:567: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  silent = bool(old_value == new_value)*

I am on Mac OS 10.10.5 with a fresh Anaconda3 install with python 3.6 and ipywidgets 7.0.1. I attached a small notebook demonstrating the issue. On my Ubuntu 16.04 with python3 I don't get this warning.

I could not find anything like this with google, so I hope the issue is genuine.

Thx,
Greg

PS: Apparantly I can not attach the notebook with a small demonstation itself, so I paste the code here:

```python
import numpy as np
from ipywidgets import interact_manual, fixed, interactive, FloatSlider, interact
from IPython.display import display

# small example array
a = np.array([1,4,6])

def foo(fac, arr):
    return fac*a

fac_Sl = FloatSlider(value = 3, min = 0, max = 10)

w = interactive(foo, fac = fac_Sl ,arr = fixed(a)) # will produce FutureWarning
display(w)

w = interactive(foo, fac = fac_Sl ,arr = fixed(20)) # will NOT produce FutureWarning
display(w)
```

**Comment by jasongrout** [comment] 2017-09-22 18:55
Thanks for filing this! This looks like it should hopefully be a straightforward fix in https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/interaction.py, so labeling with the sprint-friendly tag. If you want to work on this, feel free to ask questions!

**Comment by scottdraves** [comment] 2018-01-23 16:00
I am using master ipywidgets, python 3.6.4, and cannot reproduce.

**Comment by jasongrout** [comment] 2018-01-23 16:20
I just tried reproducing this as well, and couldn't with widgets 7.0.1 or with the master branch. I also have traitlets 4.3.2 and numpy 1.14.0.

@tensionhead - what version of traitlets and numpy do you have?

**Comment by SylvainCorlay** [comment] 2018-01-30 18:19
@jasongrout, @tensionhead

You can have such issue when using `Instance(np.ndarray)` trait, which is the *raison d'être* of the `traittypes` package. https://github.com/jupyter-widgets/traittypes

**Comment by tensionhead** [comment] 2018-01-30 18:34
Hey,

@jasongrout - it's numpy 1.13.1 and traitlets 4.3.2

and ipywidgets is actually 7.0.0 'final' according to the ipython console

@SylvainCorlay - does your comment solve the issue?

I only have ssh access to the Mac OS machine atm, but I will recheck the issue as soon as possible!

**Comment by tensionhead** [comment] 2018-01-31 11:26
Ok, so now I can not reproduce it anymore as well.. maybe I run a conda update or sth.
ipywidgets now is 7.0.0

Sorry, maybe the issue can be closed?!

**Comment by jasongrout** [comment] 2018-01-31 12:50
@tensionhead - thanks. I'll close this, and we can open a new issue if we see this again.

**Closed by jasongrout** 2018-01-31 12:50 UTC
Labels: needs info
