### ISSUE TITLE
ARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::widgetsnbextension-3.0.2-py36_0

### ISSUE THREAD

**Issue by jmbertoncelli** [jupyter-widgets/ipywidgets#1741] opened 2017-10-05 14:08 UTC
ARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::widgetsnbextension-3.0.2-py36_0

**Comment by jasongrout** [comment] 2017-10-05 15:20
Where are you seeing this error? (i.e., I'm looking for how I can reproduce it)

**Comment by blink1073** [comment] 2017-10-05 15:21
This can happen if you remove a conda environment and `notebook` gets removed before `widgetsnbextension` (not sure if it is deterministic).

**Comment by jasongrout** [comment] 2017-10-05 15:22
This looks like the same issue as https://github.com/conda-forge/widgetsnbextension-feedstock/issues/21 - does it look that way to you? If so, we should close this issue in preference to that one.

**Comment by jasongrout** [comment] 2017-10-05 15:22
> This can happen if you remove a conda environment and notebook gets removed before widgetsnbextension (not sure if it is deterministic).

That's what conda-forge/widgetsnbextension-feedstock#21 documents too.

**Comment by jasongrout** [comment] 2017-10-05 15:30
Thanks again for the report. We're tracking this at conda-forge/widgetsnbextension-feedstock#21. Feel free to re-open if you think this isn't the same issue as that.

**Closed by jasongrout** 2017-10-05 15:30 UTC
