### ISSUE TITLE
FloatSlider sometimes approximates the max and does show the desired range

### ISSUE THREAD

**Issue by joefresna** [jupyter-widgets/ipywidgets#1889] opened 2017-12-27 15:01 UTC
I use ipywidgets 7.0.5 (py35_0)
Running the following code I get a widget in the range [0.2, 0.5] instead of [0.2,0.6]:
`w = widgets.FloatSlider(value = 0.5, min = 0.2, max = 0.6, step = 0.1, description = "w")`

**Comment by jasongrout** [comment] 2018-01-02 18:36
Thanks for the bug report. I've confirmed the problem in widgets 7.1.0. I'm looking into it...

**Comment by jasongrout** [comment] 2018-01-02 18:58
This happens because of a floating point number issue, and I think the jqueryui slider we are using handles it incorrectly. When a slider's max is set, it's modified by this function: https://github.com/jquery/jquery-ui/blob/89af4c292eaa5fc1c83437ca71085264dcbef34a/ui/widgets/slider.js#L551

In that function, jqueryui tries to address roundoff error from the step by calculating what the max should be if we take the given number of steps from the min (let's call this the stepmax). However, it subtracts a whole step if the stepmax is more than the max. I think what it should do is realize that the last step may not be a full step, and set the max to what was explicitly set.

For now, a workaround is to set max to something like `0.601`.

Perhaps this is another reason for us to move off of the jqueryui slider: #630.

**Comment by jasongrout** [comment] 2018-01-02 19:01
The fundamental problem we are dealing with here is that `0.1*6 = 0.6000000000000001 > 0.6` using the computer's standard floating point number representation.

**Comment by jasongrout** [comment] 2018-01-02 19:14
Reference my comment at https://github.com/jquery/jquery-ui/pull/1664#issuecomment-354850982 - which is where the current logic is put into place.

**Comment by jasongrout** [comment] 2018-01-02 19:20
I filed a bug on their bugtracker: https://bugs.jqueryui.com/ticket/15262

**Comment by jasongrout** [comment] 2018-01-04 19:14
Another thing we could do is to specifically work around the jqueryui bug by automatically setting the slider max (and min?) to something slightly different. So in this example, our code, knowing the problems in the jqueryui code, would actually set the jqueryui slider max option to 0.600001 at https://github.com/jupyter-widgets/ipywidgets/blob/896ea55df966bb20f2d7e1829083f97d050c89cc/packages/controls/src/widget_int.ts#L158.

I think that wouldn't be too hard to implement, though it's still unfortunate that we need to do it.

**Comment by vidartf** [comment] 2022-06-17 13:07
I have confirmed (on Binder) that the new slider package on master (slated for 8.0 release) does not have this issue. Closing as fixed.

**Closed by vidartf** 2022-06-17 13:07 UTC
Labels: good first issue, resolved-locked
