### ISSUE TITLE
tqdm progressbar not showing with `vnd.jupyter.widget-view+json renderer` in vscode.

### ISSUE THREAD

**Issue by Mustapha-AJEGHRIR** [jupyter-widgets/ipywidgets#3572] opened 2022-08-27 15:19 UTC
## Description

The tqdm progressbar not showing with version ipywidgets>=8.0.0 with python==3.9.7

## Reproduce

1. Open a jupyter notebook (tested on vscode with `vnd.jupyter.widget-view+json`) with python == `3.9.7` kernel (I tested with conda)  and run the following : 
```python
from tqdm.notebook import tqdm
for _ in tqdm(range(1000_000)):
    pass
```
my version of tqdm==`4.62.3`

## Error behavior
![image](https://user-images.githubusercontent.com/66799406/187036184-e5240cb9-e314-46ec-b4df-ddf328179a32.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/66799406/187036212-e4f4a6b5-ed7b-42bc-ba34-12b4cf58e10d.png)
tested in the same configuration with ipywidgets `7.6.5`

## Context

- ipywidgets version : Error with version >= `8.0.0`, no problems with `7.6.5`
- Operating System and version: WSL on windonws 11
- jupyter version : (result of `pip list | grep jup`)
``` python
jupyter                       1.0.0
jupyter-client                7.2.0
jupyter-console               6.4.4
jupyter-core                  4.9.2
jupyterlab-pygments           0.2.2
jupyterlab-widgets            3.0.2
```
- Tested on : Vscode code 1.70.2

**Comment by lukasbindreiter** [comment] 2022-08-29 08:55
Probably related to this: https://github.com/tqdm/tqdm/issues/1359

**Comment by jasongrout** [comment] 2022-08-29 14:50
Thanks for reporting this. We're tracking the more specific root cause over in #3576, so I'll close this to consolidate discussion over to that issue.

**Closed** 2022-08-29 14:50 UTC
Labels: resolved-locked
