### ISSUE TITLE
Add a continuous_update option for text widgets

### ISSUE THREAD

**Issue by jasongrout** [jupyter-widgets/ipywidgets#584] opened 2016-05-13 03:28 UTC
The sliders have a continuous_update option that only triggers a value change when the user stops dragging a slider: https://github.com/ipython/ipywidgets/blob/master/ipywidgets/widgets/widget_int.py#L155. Likewise, the text boxes should have an option to only update the value when the text box is blurred, or maybe when the user presses enter in a one-line textbox (sort of the equivalent of the on_submit handler textboxes currently have).

**Comment by dhirschfeld** [comment] 2016-05-15 23:06
An event which triggers on enter or when a user leaves the text box would be useful. The current `on_submit` can be confusing if the user forgets to press enter, the text has changed but the handler hasn't triggered so the text in the box won't necessarily be related to the state of the widget.

**Comment by jasongrout** [comment] 2016-05-16 14:47
+1 to the UI indication of a 'dirty' textbox.

**Comment by codypiersall** [comment] 2017-04-27 14:56
+1 for this!  I wrote a notebook that uses ipywidgets to control a motor, and had to use a `Text` widget because the hardware would ignore commands while it was already doing something.  But a BoundedFloatText was conceptually better!  @dhirschfeld's idea is perfect -- update when the box loses focus or the user hits the return key.

Would a pull request implementing this be likely to be merged?

**Comment by jasongrout** [comment] 2017-04-27 15:21
> Would a pull request implementing this be likely to be merged?

Yes, very likely!

**Comment by codypiersall** [comment] 2017-04-27 19:07
I'd love to work on this, but if someone else wants to please go ahead!  I probably won't have time for about the next month, but after I'm done with my current side project I'll give this a whirl.  All this to say...

If someone comes across this post in about a month and I haven't re-posted, feel free to ping me!

**Comment by jasongrout** [comment] 2017-04-27 19:39
Thanks! I've also marked it as sprint-friendly, so it'll be easier for new contributors to find.

**Comment by jasongrout** [comment] 2017-07-26 18:40
ping @codypiersall, as requested. Someone else just asked for this today too.

**Comment by jasongrout** [comment] 2017-07-26 18:55
To implement this, I would:

1. Make a continuous_update attribute analogous to the slider's attribute at https://github.com/jupyter-widgets/ipywidgets/blob/673e42da500d6a416ffd7e77cf408af08158918c/ipywidgets/widgets/widget_int.py#L161 on the textboxes (https://github.com/jupyter-widgets/ipywidgets/blob/673e42da500d6a416ffd7e77cf408af08158918c/ipywidgets/widgets/widget_string.py#L73, https://github.com/jupyter-widgets/ipywidgets/blob/673e42da500d6a416ffd7e77cf408af08158918c/ipywidgets/widgets/widget_string.py#L61, https://github.com/jupyter-widgets/ipywidgets/blob/673e42da500d6a416ffd7e77cf408af08158918c/ipywidgets/widgets/widget_float.py#L63, https://github.com/jupyter-widgets/ipywidgets/blob/673e42da500d6a416ffd7e77cf408af08158918c/ipywidgets/widgets/widget_float.py#L80, and the inttext widgets too)
2. In the javascript code to each of the views, handle continous updates with the `input` event, and non-continuous updates with the `change` event.

**Closed** 2017-07-31 13:37 UTC
Labels: feature request, sprint-friendly

**Comment by spiros96175** [comment] 2020-09-25 16:55
hello i have a problem about my project in jupyter notebook . The problem is that in editor mode the drop down menus runs normally and correct but when i save it, at the view mode the second drop menu dont run
