### ISSUE TITLE
Scroll Bar not displayed using output widgets and IPython.display

### ISSUE THREAD

**Issue by enryH** [jupyter-widgets/ipywidgets#2778] opened 2020-02-11 16:48 UTC
Dear Team,
I cannot see the scroll bar when I use the [example from @jasongrout](https://github.com/jupyter-widgets/ipywidgets/issues/1319#issuecomment-298063921) (on a windows machine both in notebook and jupterlab). Any Idea how to solve that?

So: 
```python
import pandas as pd
from ipywidgets import *
from IPython.display import display
import numpy as np

w_dims = IntSlider()

out = Output()
with out:
    display(pd.DataFrame(np.random.randn(10,300)))

display(HBox([out]))
```
gives
![image](https://user-images.githubusercontent.com/2833836/74256073-22a19480-4cf3-11ea-85a4-b3736d7de17b.png)

whereas

```python
import pandas as pd
from ipywidgets import *
from IPython.display import display
import numpy as np
display(pd.DataFrame(np.random.randn(5,300)))
```
yields what I expect:
![image](https://user-images.githubusercontent.com/2833836/74256278-685e5d00-4cf3-11ea-9817-f0c6825ab82f.png)

(I need it for a more involved example, but I thought to start easy)

Thanks in advance!

**Comment by jasongrout** [comment] 2020-02-11 17:22
Looking into it, it seems that the `overflow:visible` css from the `jupyter-widgets` css class is overriding the JupyterLab `overflow:auto` css:
<img width="1370" alt="Screen Shot 2020-02-11 at 8 43 33 AM" src="https://user-images.githubusercontent.com/192614/74261170-a8035580-4caf-11ea-9245-14c5911518f8.png">

Disabling the `overflow:visible` class for `.jupyter-widgets` fixes the issue. One way to fix this is to make more specific `.jupyter-widgets.jp-OutputArea-output {overflow: auto}` to override the jupyter-widgets default css.

I'm not sure that having `overflow:visible` as a default is a good idea in general. We have had it for a long time, so it break things quite a bit if we change it now, though.

**Comment by jasongrout** [comment] 2020-02-11 17:23
Here is the line with that css: https://github.com/jupyter-widgets/ipywidgets/blob/fa3c7066622a8cd869f1306033c5e8bf400bc2fb/packages/controls/css/widgets-base.css#L67

**Comment by jasongrout** [comment] 2020-02-11 17:27
Actually, looking at the DOM again, https://github.com/jupyter-widgets/ipywidgets/pull/2500 is an important fix here, in that the jupyter-widgets class that is overriding the overflow is at the root widget render, not just on the output widget.

**Comment by jasongrout** [comment] 2020-02-11 17:27
So actually this issue may be a duplicate of https://github.com/jupyter-widgets/ipywidgets/issues/2499 (i.e., same cause and fix)?

**Comment by enryH** [comment] 2020-02-11 17:30
So I have to set `overflow: auto` in my local installation of ipywidgets? Or can I do this within a notebook only for the use-case at hand?

**Comment by jasongrout** [comment] 2020-02-11 17:42
I just merged #2500 and tested, and it looks like that solved the issue in JupyterLab. Unfortunately, the fix won't be easy to make (essentially you'd have to tweak the ipywidgets extension to basically apply #2500). It will be in our next release, coming very soon, though.

**Comment by jasongrout** [comment] 2020-02-11 17:50
One (not very satisfactory, but maybe sufficient?) workaround is to set an explicit width for your output widget, like `out.layout.width='400px'`.

**Comment by jasongrout** [comment] 2020-02-11 17:51
Closing since #2500 fixes this and has been merged.

**Closed by jasongrout** 2020-02-11 17:51 UTC

**Comment by jasongrout** [comment] 2020-02-11 17:52
> Closing since #2500 fixes this and has been merged.

But feel free to continue the discussion if you'd like to talk about this or workarounds more.

**Comment by enryH** [comment] 2020-02-12 08:52
Thank you very much @jasongrout ! I will restrict the width for now and since it's updated, I won't have to worry about it for too long anyways:)
