### ISSUE TITLE
ipywidgets Dropdown menu ignores description

### ISSUE THREAD

**Issue by jukent** [jupyter-widgets/ipywidgets#2502] opened 2019-07-16 17:07 UTC
I am creating a widget for a code that randomly assigns the users musical scales to practice. The option for what type of scale (Modality) is a dropdown widget, but I think there is a bug, since the label beside the widget is not changing with 'description'

Here is the widget portion of my code:
![Screen Shot 2019-07-16 at 11 06 58 AM](https://user-images.githubusercontent.com/46687291/61314448-d96b7f80-a7b9-11e9-952a-584c4d8b7485.png)

The label next to the drop down widget should be 'Select Modality' not 'Modality'.

**Comment by pbugnion** [comment] 2020-01-08 14:21
Thanks for raising this, and apologies for the late reply.

I can't reproduce this at all on ipywidgets 7.5.1:

```py
import ipywidgets as widgets

def show_result(result):
    print(result)

widgets.interactive(
    show_result, 
    result=widgets.Dropdown(options=["a", "b", "c"], description="hello")
)
```

<img width="709" alt="Screenshot 2020-01-08 at 14 21 36" src="https://user-images.githubusercontent.com/1392879/71985239-1c1a8b80-3222-11ea-8d24-dac86e048b88.png">

I'm closing this as fixed, but feel free to re-open if you're still facing this.

**Closed by pbugnion** 2020-01-08 14:21 UTC
