### ISSUE TITLE
Widgets not rendering in static html output

### ISSUE THREAD

**Issue by TimShawver** [jupyter-widgets/ipywidgets#1597] opened 2017-08-06 21:18 UTC
I've been working on refactoring [qgrid](https://github.com/quantopian/qgrid) to use the latest best practices for widgets as defined by the the [widget-cookiecutter](https://github.com/jupyter-widgets/widget-cookiecutter) project.

For the most part things have gone pretty smoothly but I'm having trouble getting it to render in the static html output that's created by clicking "Download as HTML".  And actually I'm currently unable to get any widgets to render in that html output, so this problem is not specific to qgrid (I just mentioned qgrid to give you some context about what I'm working on).

I actually had this working before, but I must've either done something to my environment or upgrading ipywidgets broke this.  I think what worked for me in the past was clicking "Save Notebook Widget State" and then "Download as HTML" from the menu inside the notebook.  Now when I do that, widgets don't appear in the resulting generated HTML file, and I see a bunch of errors in the javascript console:

![screen shot 2017-08-06 at 5 05 10 pm](https://user-images.githubusercontent.com/5055866/29007072-9332b9bc-7ac9-11e7-967e-f963bc42c6d2.png)

As you can see, the html preview is attempting to load version 1.0.0 of @jupyter-widgets/base, which doesn't exist, and I can't figure out why it's trying to load that version.

I'm currently using notebook 5.0.0 and ipywidgets 7.0.0b7, but I've tried a bunch of different versions of ipywidgets and haven't had any luck, except for the one time I mentioned above.

Thanks in advance for the help, and for this awesome project. I'm really excited about allowing people to use qgrid in jupyterlab etc.

**Comment by jasongrout** [comment] 2017-08-09 14:19
The fact it is referencing jupyter-js-widgets 2.0.* indicates that something is not upgraded, or perhaps you need to clear the widget state in the notebook. Can you post an example notebook with this issue?

**Comment by TimShawver** [comment] 2017-08-10 02:02
Sure, here's an example notebook file: https://gist.githubusercontent.com/TimShawver/a02bf3cd48fd2357df25c38a6970dbdf/raw/180319b91c4dfdbbe6544b8e8002f136aa2d4236/download_as_html.ipynb

FWIW I was able to get this working on ipywidgets 6.0.  Initially I had trouble getting it working with that version too, and I think what fixed it was emptying out some old installations that were left in the various "data" paths that get listed out when I run `jupyter --paths`.  My best guess is I ran `jupyter nbextension install` with `--user` or `--system` at some point, resulting in me having some old versions laying around in the `nbextensions` folders of the various "data" paths.

That being said, it seems like doing that cleanup still didn't fix this issue I'm seeing with ipywidgets 7.0.0b8, so I still could use some help with getting this working on version 7 (although it's a bit lower priority for me now since I have it working on version 6).  I'm fairly certain I had it working at one point tonight after clearing out the existing `nbextensions/jupyter-js-widgets` folder within my virtualenv and reinstalling with `pip install ipywidgets --pre`.  But then I changed some stuff (I think reinstalled ipywidgets and installed qgrid) and now I'm back to getting basically the same error as before (even after uninstalling qgrid and trying to start over in a fresh virtual env).  

Here's another screen shot of the js console, because there was a version mismatch message printed out that was collapsed and not shown in the original screen shot:

![screen shot 2017-08-09 at 9 27 14 pm](https://user-images.githubusercontent.com/5055866/29150603-b3fe111e-7d49-11e7-99fc-60f023b36c9c.png)

**Comment by jasongrout** [comment] 2017-08-10 03:25
Can you also (a) try with beta 9? I was making some fixes to that part of the code, and also (b) post your HTML file that you are generating?

**Comment by TimShawver** [comment] 2017-08-10 15:58
I'm seeing the same errors with beta 9.  Here's the generated html file, using beta 9: https://gist.githubusercontent.com/TimShawver/a02bf3cd48fd2357df25c38a6970dbdf/raw/3ecfc57d1b5723b9183bdb416763f335af7d76da/download_as_html.html

**Comment by jasongrout** [comment] 2017-08-10 16:01
Ah, I think the issue is that nbconvert needs to be upgraded to handle the new widget version: https://github.com/jupyter/nbconvert/issues/636

**Comment by TimShawver** [comment] 2017-08-10 16:08
Ah OK.  Good to know it's not an issue on my end.

**Comment by jasongrout** [comment] 2017-10-20 20:32
Tracking the nbconvert issue in jupyter/nbconvert#636, so closing this.

**Closed by jasongrout** 2017-10-20 20:32 UTC

**Comment by daniilhayrapetyan** [comment] 2018-05-25 17:13
Have the same issue here
![screenshot from 2018-05-25 21-09-27](https://user-images.githubusercontent.com/26569802/40557108-1d65bee6-6060-11e8-9733-ab266ecf5f4d.png)

```
jupyter                            1.0.0                 
jupyter-client                     5.2.3                 
jupyter-console                    5.2.0                 
jupyter-contrib-core               0.3.3                 
jupyter-contrib-nbextensions       0.5.0                 
jupyter-core                       4.4.0                 
jupyter-highlight-selected-word    0.2.0                 
jupyter-latex-envs                 1.4.1                 
jupyter-nbextensions-configurator  0.4.0                 
jupyterlab                         0.31.8                
jupyterlab-launcher                0.10.5                
jupyterthemes                      0.19.1   
ipykernel                          4.8.2                 
ipython                            5.7.0                 
ipython-genutils                   0.2.0                 
ipywidgets                         7.2.1  
widgetsnbextension                 3.2.1   
```
