### ISSUE TITLE
Cannot clear output of cell when cell is an Output widget

### ISSUE THREAD

**Issue by mwcraig** [jupyter-widgets/ipywidgets#1484] opened 2017-07-06 04:04 UTC
I can reproduce this with a fairly simple notebook. This will do it, the gif below has a couple more cells to illustrate that the Output is still active even after attempting to clear:

```python
import ipywidgets as widgets
print(widgets.__version__)
out = widgets.Output()
out
```
Video of the problem:

![no-clear-output](https://user-images.githubusercontent.com/1147167/27895143-36966444-61d6-11e7-958f-04eea501bbc0.gif)

javascript console:

```
events.js:33 Exception in event handler for clear_output.CodeCell TypeError: Cannot read property 'el' of undefined
    at extension.js:65
    at Array.forEach (<anonymous>)
    at window._Events.removeView (extension.js:60)
    at window._Events.dispatch (jquery.min.js:5)
    at window._Events.y.handle (jquery.min.js:5)
    at Object.trigger (jquery.min.js:5)
    at window._Events.<anonymous> (jquery.min.js:5)
    at Function.each (jquery.min.js:4)
    at init.each (jquery.min.js:4)
    at init.trigger (jquery.min.js:5) 
(2) ["clear_output.CodeCell", Object, callee: (...), Symbol(Symbol.iterator): function]
```
```
extension.js:65 Uncaught TypeError: Cannot read property 'el' of undefined
    at extension.js:65
    at Array.forEach (<anonymous>)
    at HTMLDivElement.removeView (extension.js:60)
    at HTMLDivElement.dispatch (jquery.min.js:5)
    at HTMLDivElement.y.handle (jquery.min.js:5)
    at Object.trigger (jquery.min.js:5)
    at HTMLDivElement.<anonymous> (jquery.min.js:5)
    at Function.each (jquery.min.js:4)
    at init.each (jquery.min.js:4)
    at init.trigger (jquery.min.js:5)
```

**Comment by jasongrout** [comment] 2017-07-06 04:07
Thanks for such an extensive report!

**Comment by vidartf** [comment] 2017-07-06 11:14
This seems similar to #1413, which was previously closed.

**Comment by jasongrout** [comment] 2017-07-06 21:13
What version of the notebook are you on? I couldn't reproduce this when I just tried with notebook 5.0.0 and ipywidgets master.

**Comment by jasongrout** [comment] 2017-07-06 21:15
Can you click on the error line number and see what line is triggering the error?

**Comment by mwcraig** [comment] 2017-07-07 00:29
Right now none of my widgets will clear, and the students I ran the tutorial with today didn't hit the problem. Let me see if some cache clearing, etc helps...

**Comment by mwcraig** [comment] 2017-07-07 01:57
This is *not* happening in a clean `widgets-2017` environment, so I don't think it is high priority. Something about my dev environment is messed up, but it isn't critical to solve.

**Comment by jasongrout** [comment] 2017-07-07 04:07
Okay. I'll close this for now, and if you can reproduce your error with a clean setup, please reopen.

**Closed by jasongrout** 2017-07-07 04:07 UTC
Labels: needs info
