### ISSUE TITLE
Class OutputModel not found in module jupyter-js-widgets

### ISSUE THREAD

**Issue by ischurov** [jupyter-widgets/ipywidgets#1183] opened 2017-03-04 21:49 UTC
I'm actually do not understand how brand new "rendering widgets in nbviewer" is expected to work, but I found, how it is not working.

I created a simple demo plotting a graph with `matplotlib.pyplot` and two sliders. It works in Jupyter but does not work in nbviewer.

The code is the following:

```python
import ipywidgets as widgets
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

@widgets.interact(a=widgets.FloatSlider(min=0, max=10, value=1, step=1e-3), 
          b=widgets.FloatSlider(min=0, max=10, value=1, step=1e-3))
def plot_sin(a, b):
    x = np.linspace(-4,4,300)
    plt.ylim(-2,2)
    plt.plot(np.sin(a*x)*b)
    plt.show()
```

Then I selected *Widgets → Save Notebook with Widgets* menu item, then uploaded ipynb-file to the server, then opened with nbviewer, see [the link](http://nbviewer.jupyter.org/url/schurov.com/widgets.ipynb?flush_cache=true).

The actual sliders are rendered, but the output is not and I have the following error message instead of rendered content:

```
Could not create model:
Model name	OutputModel
Model module	jupyter-js-widgets
Model module version	~2.1.4
Class OutputModel not found in module jupyter-js-widgets
```

Actually, I didn't expect that my pictures will be shown correctly as they are dynamically created (depending on the positions of the sliders) on python side and nbviewer does not execute Python code. (The behaviour I theoretically might expect is that Jupyter tries to generate all possible combinations of pictures and instruct nbviewer to show the correct one depending on sliders, but it is obviously very time and space-consuming thing, especially if several widgets presented.) Anyway, currently the error message seem to be unclear for me. Is it a bug? A feature?

**Comment by janfreyberg** [comment] 2017-03-05 09:57
+1, having the same issue with `pyplot.imshow()`. I get the exact same error message.

Mine is here:
http://nbviewer.jupyter.org/gist/janfreyberg/496e9d3f4a5ff2d41e7e0f3e60063ac4

**Comment by SylvainCorlay** [comment] 2017-03-05 10:56
That is right. The output widget used by interact is the only widget not supported in web contexts other than notebook and lab.

Since multiple people are affected by this, I make this a priority for 6.0.1.

**Comment by janfreyberg** [comment] 2017-03-05 11:01
Ah, that's great to know. Thanks!

**Comment by maartenbreddels** [comment] 2017-04-04 18:41
Also hit by this [here](http://ipyvolume.readthedocs.io/en/latest/bokeh.html), good to see this is reported.

**Comment by jasongrout** [comment] 2017-04-04 21:36
Closing as a duplicate of #986.

**Closed by jasongrout** 2017-04-04 21:36 UTC
