### ISSUE TITLE
JavaScript Chunking Error

### ISSUE THREAD

**Issue by ajennings67** [jupyter-widgets/ipywidgets#2637] opened 2019-12-09 20:35 UTC
Hi,

I recently installed ipyaggrid to use in conjunction with ipywidgets. After install ipyaggrid, my ipywidgets scripts stopped working:

![ipywidgets](https://user-images.githubusercontent.com/25620161/70470551-3c2b2380-1a99-11ea-85ea-130861bd54ff.PNG)

`conda list`:

```
conda list
# packages in environment at /home/qmacro/anaconda3/envs/dma_qa_compare:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
altair                    3.2.0                    py37_0
arrow-cpp                 0.13.0           py37h117bdfb_0
attrs                     19.3.0                     py_0
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl
bleach                    3.1.0                      py_0    conda-forge
boost-cpp                 1.67.0               h14c3975_4
brotli                    1.0.7                he6710b0_0
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2019.11.27                    0
certifi                   2019.11.28               py37_0
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
double-conversion         3.1.5                he6710b0_1
entrypoints               0.3                      py37_0
gflags                    2.2.2                he6710b0_0
glog                      0.4.0                he6710b0_0
icu                       58.2                 h9c2bf20_1
importlib_metadata        1.1.0                    py37_0
intel-openmp              2019.4                      243
ipyaggrid                 0.2.0                    pypi_0    pypi
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipysheet                  0.4.3                      py_1    conda-forge
ipython                   7.10.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.3                     py_0
jsonschema                3.2.0                    py37_0
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
libboost                  1.67.0               h46d08c1_4
libedit                   3.1.20181209         hc058e9b_0
libevent                  2.1.8                h1ba5d50_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libprotobuf               3.6.0                hdbcaa40_0
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
lz4-c                     1.8.1.2              h14c3975_0
markupsafe                1.1.1            py37h7b6447c_0
mistune                   0.8.4           py37h516909a_1000    conda-forge
mkl                       2019.4                      243
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.0.15           py37ha843d7b_0
mkl_random                1.1.0            py37hd6b4f25_0
more-itertools            7.2.0                    py37_0
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  he6710b0_1
notebook                  6.0.1                    py37_0    conda-forge
numpy                     1.17.4           py37hc1035e2_0
numpy-base                1.17.4           py37hde5b4d6_0
openssl                   1.1.1d               h7b6447c_3
pandas                    0.25.3           py37he6710b0_0
pandoc                    2.8.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.3.1                   py37_0
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            3.0.2                      py_0    conda-forge
pscript                   0.7.1                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pyarrow                   0.13.0           py37he6710b0_0
pygments                  2.5.2                      py_0    conda-forge
pyodbc                    4.0.27           py37he6710b0_0
pyrsistent                0.15.6           py37h7b6447c_0
python                    3.7.5                h0371630_0
python-dateutil           2.8.1                      py_0
pytz                      2019.3                     py_0
pyzmq                     18.1.1           py37h1768529_0    conda-forge
re2                       2019.08.01           he6710b0_0
readline                  7.0                  h7b6447c_5
send2trash                1.5.0                      py_0    conda-forge
setuptools                42.0.2                   py37_0
simplejson                3.17.0                   pypi_0    pypi
six                       1.13.0                   py37_0
snappy                    1.1.7                hbae5bb6_3
sqlite                    3.30.1               h7b6447c_0
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thrift-cpp                0.11.0               h02b749d_3
tk                        8.6.8                hbc83047_0
toolz                     0.10.0                     py_0
tornado                   6.0.3            py37h516909a_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
unixodbc                  2.3.7                h14c3975_0
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0
widgetsnbextension        3.5.1                    py37_0    conda-forge
xz                        5.2.4                h14c3975_4
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                      py_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0
```

Please let me know what other information you might need!

Thanks,

Austin

**Comment by jasongrout** [comment] 2019-12-10 19:14
CC @DGothrek  and @oscar6echo, who I think are the ipyaggrid maintainers.

Nothing looks amiss at a quick glance. Can you follow the guidelines at https://jupyterlab.readthedocs.io/en/stable/getting_started/issue.html to try to reproduce it in a clean environment?

**Comment by oscar6echo** [comment] 2019-12-11 11:26
Thx @jasongrout 

I'll try and correct if there is a pb with ipyaggrid - that I can reproduce.

**Comment by ajennings67** [comment] 2019-12-11 21:11
Thanks guys for your prompt response! Sorry for not starting with the reproducible example. 

In the process of recreating in a docker container, I was unable to reproduce the exact issue, but did experience something quite similar:

```
docker pull ajennings67/ipyaggrid:test1
```

```
from ipyaggrid import Grid
from IPython.display import display
from ipywidgets import IntSlider
import pandas as pd

f = IntSlider(min=0, max=100)
display(f)

df = pd.DataFrame(data=[['A', 'B', 'C'], ['D', 'E', 'F']], columns=['1', '2', '3'])

grid_options = {
    'enableSorting': True,
}

Grid(grid_data=df, grid_options=grid_options)
```
Visually:

![grid](https://user-images.githubusercontent.com/25620161/70660474-46335a80-1c30-11ea-922d-3d30bd05b394.PNG)

Console:
![image](https://user-images.githubusercontent.com/25620161/70660564-81ce2480-1c30-11ea-8456-a146a02ce9c3.png)

I installed ipywidgets, ipyaggrid, and the extension manager manually in jupyterlab.

**Comment by oscar6echo** [comment] 2019-12-28 00:55
Finally I had time to test.  
I can reproduce the bug in a clean conda env where I install jupyterlab ipywidgets and ipyaggrid.  
But it does work fine for classic notebook (unsurprisingly as it is what we use in prod). So it must be some JupyterLab glue code issue ?..  
Unfortunately I know very little about JLab specifics. I got the initial inspiration from [ipysheet](https://github.com/QuantStack/ipysheet) and the official [jupyter widgets cookiecutter](https://github.com/jupyter-widgets/widget-cookiecutter). Apparently something changed in JLab extensions authoring since ipyaggrid v0.1.0 was published. However unless I'm mistaken the ipyaggrid [labplugin.js](https://gitlab.com/DGothrek/ipyaggrid/blob/master/js/src/labplugin.js) and [webpack.config.js](https://gitlab.com/DGothrek/ipyaggrid/blob/master/js/webpack.config.js) files seem still ok. I have not idea where else to look and more generally how to go from a functioning widget in classic notebook to the same in JLab... 
 
For reference here is some info on my config:
```bash
jupyter labextension list
JupyterLab v1.2.4
Known labextensions:
   app dir: /usr/local/miniconda3/envs/grid/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        ipyaggrid v0.2.0  enabled  OK*

   local extensions:
        ipyaggrid: /Users/Olivier/Documents/dev/ipyaggrid/js
```

and the first error msg says:
```bash
bootstrap:149 GET http://localhost:8889/nullnbextensions/ipyaggrid/vendors~@jupyter-widgets/controls.654921dea193c48df613.js net::ERR_ABORTED 404 (Not Found)
```

**Comment by MTereM** [comment] 2020-02-18 10:48
Hi,

I'm having the same issue! ipywidgets were working just fine until I installed ipyaggrid, after that they stopped working. Any ideas on how I can solve this?

**Comment by ismael-benitez** [comment] 2020-04-08 00:57
Hi,

I did a fresh installation and I had the same problem with ipyaggrid in jlab 2.0.1.

`$ jupyter labextension list
JupyterLab v2.0.1
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @bokeh/jupyter_bokeh v2.0.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        ipyaggrid v0.2.0  enabled  OK
        jupyter-matplotlib v0.7.2  enabled  OK
`

![image](https://user-images.githubusercontent.com/5638973/78733068-402e5b80-793c-11ea-94fc-1e89f1799ef8.png)

Any news?

**Comment by ismael-benitez** [comment] 2020-04-08 01:04
Maybe this screenshoot about the console with the javascript log can help you

![image](https://user-images.githubusercontent.com/5638973/78733356-20e3fe00-793d-11ea-85d7-0ee6c9bd4d74.png)

**Comment by leonidsopotnitskiy** [comment] 2020-11-15 14:48
has anyone found a solution to this?

**Comment by aristidesnakos** [comment] 2020-12-06 00:21
@leonidsopotnitskiy The problem seems to be around **JupyterLab**. Once you run the code in _Jupyter Classic_, the ipyaggrid works fine. It's as @oscar6echo said above ^.

**Comment by jasongrout** [comment] 2020-12-06 01:04
Can you file an issue with ipyaggrid, which I think is at https://gitlab.com/DGothrek/ipyaggrid? It looks like ipywidgets itself is working just fine.

Closing, since it doesn't seem to be an issue with ipywidgets itself.

**Closed by jasongrout** 2020-12-06 01:04 UTC

**Comment by jasongrout** [comment] 2020-12-06 01:23
FYI, out of curiousity, I installed the latest JupyterLab, ipywidgets, and ipyaggrid, and the worked fine for me: see https://github.com/jupyterlab/jupyterlab/issues/8176#issuecomment-739440093 for more details.
