### ISSUE TITLE
interact broken with matplotlib on 6.x

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-widgets/ipywidgets#1457] opened 2017-06-26 16:49 UTC
HI all, pulled up some demos of using interact with matplotlib for a talk today and saw that interact doesn't work with matplotlib on 6.x stable. You end up with multiple plots showing, seems like clear output isn't happening. Other output types seem to work fine.

**Comment by jasongrout** [comment] 2017-06-26 17:51
Can you post example code exposing the problem?

**Comment by jasongrout** [comment] 2017-06-26 17:52
Is it this issue? https://github.com/jupyter-widgets/ipywidgets/issues/1181#issuecomment-284172632

**Comment by jasongrout** [comment] 2017-06-30 01:55
ping @ellisonbg - does using `plt.show()` in the interact fix the issue?

**Comment by ellisonbg** [comment] 2017-06-30 02:47
I think it is the same issue and adding `plt.show` does fix it. But this usage case is extremely common and we have always made strong promises that interact will "just work" with matplotlib. I know *a lot* about Matplotlib, I wrote the original version of interact, and follow ipywidgets reasonably closely. Even I had absolutely no idea why it would behave this way. It actually took me a very long time to realize it was something specific to matplotlib and not interact in general. I just figured interact was broken so I had stopped using it in all my talks.

Even though this behavior changed in a major release, I don't think this is a change our users will tolerate (there is nothing that points them to the problem+solution) and I think we should fix it and release a bug fix for 6.x.

A comment on why Matplotlib+interact is so important. Most other modern plotting libraries that are based on JavaScript (Altair, BQPlot, Bokeh) are too slow to work really well with basic interact. Sure something like BQPlot can be hooked up to ipywidgets in more complex ways, but the attraction of interact is that all that isn't required for simple things. With matplotlib+interact, you get a long way with just interact. I have some really nice examples of matplotlib+interact based code that allows a user to explore a statistical model/etc with an extremely simple interact call.

**Comment by jasongrout** [comment] 2017-06-30 02:58
As pointed out in https://github.com/ipython/ipython/issues/10376#issuecomment-284036014, we can special-case it.

**Comment by jasongrout** [comment] 2017-06-30 03:00
Can we carry this discussion on in https://github.com/ipython/ipython/issues/10376, where we have already discussed it extensively? There are a lot of subtle edge cases with special-casing things to work automatically.

**Comment by jasongrout** [comment] 2017-06-30 03:13
Setting to 7.0 - we might implement the flush_figure workaround from https://github.com/ipython/ipython/issues/10376

**Comment by ellisonbg** [comment] 2017-06-30 03:36
Sure, feel free to close this one.

**Comment by jasongrout** [comment] 2017-06-30 11:05
I'll close this as a duplicate of #1181, which I've reopened to track our implementation here of the workaround.

**Closed by jasongrout** 2017-06-30 11:05 UTC
