### ISSUE TITLE
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control

### ISSUE THREAD

**Issue by LukaPitamic** [jupyter-widgets/ipywidgets#3454] opened 2022-05-07 12:10 UTC
## Description

When new kernel session is instantiated(new notebook) JLab logs:
`[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control`  
`[IPKernelApp] WARNING | No such comm: ded5178f-d06f-422a-851f-d7a4b564debb` 

Below is the context I just tried, but I tried with a lot of different versions combinations. 

## Reproduce

1. clean env creation: `conda create -n ipywidgets_problem jupyterlab ipywidgets -y`
2. activate env: `conda activate ipywidgets_problem`
3. run JLab: `jupyter lab`

## Context

- ipywidgets version: 7.7.0
- JLab version: 3.4.0
- Operating System and version: Linux Ubuntu 20
- Browser and version: any, tried on Firefox, Brave, Safari

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/luka/miniconda3/envs/ipywidgets_problem/bin
	/home/luka/miniconda3/condabin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/home/luka/miniconda3/envs/ipywidgets_problem/bin
	/home/luka/miniconda3/envs/ipywidgets_problem/lib/python310.zip
	/home/luka/miniconda3/envs/ipywidgets_problem/lib/python3.10
	/home/luka/miniconda3/envs/ipywidgets_problem/lib/python3.10/lib-dynload
	/home/luka/miniconda3/envs/ipywidgets_problem/lib/python3.10/site-packages

sys.executable:
	/home/luka/miniconda3/envs/ipywidgets_problem/bin/python

sys.version:
	3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:39:04) [GCC 10.3.0]

platform.platform():
	Linux-5.11.22-4-pve-x86_64-with-glibc2.31

which -a jupyter:
	/home/luka/miniconda3/envs/ipywidgets_problem/bin/jupyter

pip list:
	Package              Version
	-------------------- ---------
	anyio                3.5.0
	argon2-cffi          21.3.0
	argon2-cffi-bindings 21.2.0
	asttokens            2.0.5
	attrs                21.4.0
	Babel                2.10.1
	backcall             0.2.0
	beautifulsoup4       4.11.1
	bleach               5.0.0
	brotlipy             0.7.0
	certifi              2021.10.8
	cffi                 1.15.0
	charset-normalizer   2.0.12
	cryptography         36.0.0
	debugpy              1.6.0
	decorator            5.1.1
	defusedxml           0.7.1
	entrypoints          0.4
	executing            0.8.3
	fastjsonschema       2.15.3
	idna                 3.3
	importlib-metadata   4.11.3
	importlib-resources  5.7.1
	ipykernel            6.13.0
	ipython              8.3.0
	ipython-genutils     0.2.0
	ipywidgets           7.7.0
	jedi                 0.18.1
	Jinja2               3.1.2
	json5                0.9.6
	jsonschema           4.5.1
	jupyter-client       7.3.0
	jupyter-core         4.10.0
	jupyter-server       1.17.0
	jupyterlab           3.4.0
	jupyterlab-pygments  0.2.2
	jupyterlab-server    2.13.0
	jupyterlab-widgets   1.1.0
	MarkupSafe           2.1.1
	matplotlib-inline    0.1.3
	mistune              0.8.4
	nbclassic            0.3.7
	nbclient             0.6.2
	nbconvert            6.5.0
	nbformat             5.4.0
	nest-asyncio         1.5.5
	notebook             6.4.11
	notebook-shim        0.1.0
	packaging            21.3
	pandocfilters        1.5.0
	parso                0.8.3
	pexpect              4.8.0
	pickleshare          0.7.5
	pip                  22.0.4
	prometheus-client    0.14.1
	prompt-toolkit       3.0.29
	psutil               5.9.0
	ptyprocess           0.7.0
	pure-eval            0.2.2
	pycparser            2.21
	Pygments             2.12.0
	pyOpenSSL            22.0.0
	pyparsing            3.0.8
	pyrsistent           0.18.1
	PySocks              1.7.1
	python-dateutil      2.8.2
	pytz                 2022.1
	pyzmq                22.3.0
	requests             2.27.1
	Send2Trash           1.8.0
	setuptools           62.1.0
	six                  1.16.0
	sniffio              1.2.0
	soupsieve            2.3.1
	stack-data           0.2.0
	terminado            0.13.3
	tinycss2             1.1.1
	tornado              6.1
	traitlets            5.1.1
	typing_extensions    4.2.0
	urllib3              1.26.9
	wcwidth              0.2.5
	webencodings         0.5.1
	websocket-client     1.3.2
	wheel                0.37.1
	widgetsnbextension   3.6.0
	zipp                 3.8.0

conda list:
	# packages in environment at /home/luka/miniconda3/envs/ipywidgets_problem:
	#
	# Name                    Version                   Build  Channel
	_libgcc_mutex             0.1                 conda_forge    conda-forge
	_openmp_mutex             4.5                       2_gnu    conda-forge
	anyio                     3.5.0           py310h06a4308_0  
	argon2-cffi               21.3.0             pyhd3eb1b0_0  
	argon2-cffi-bindings      21.2.0          py310h7f8727e_0  
	asttokens                 2.0.5              pyhd3eb1b0_0  
	attrs                     21.4.0             pyhd3eb1b0_0  
	babel                     2.10.1             pyhd8ed1ab_0    conda-forge
	backcall                  0.2.0              pyhd3eb1b0_0  
	beautifulsoup4            4.11.1          py310h06a4308_0  
	bleach                    5.0.0              pyhd8ed1ab_0    conda-forge
	brotlipy                  0.7.0           py310h7f8727e_1002  
	bzip2                     1.0.8                h7b6447c_0  
	ca-certificates           2022.4.26            h06a4308_0  
	certifi                   2021.10.8       py310hff52083_2    conda-forge
	cffi                      1.15.0          py310hd667e15_1  
	charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
	cryptography              36.0.0          py310h9ce1e76_0  
	debugpy                   1.6.0           py310hd8f1fbe_0    conda-forge
	decorator                 5.1.1              pyhd3eb1b0_0  
	defusedxml                0.7.1              pyhd3eb1b0_0  
	entrypoints               0.4             py310h06a4308_0  
	executing                 0.8.3              pyhd3eb1b0_0  
	idna                      3.3                pyhd3eb1b0_0  
	importlib-metadata        4.11.3          py310h06a4308_0  
	importlib_metadata        4.11.3               hd3eb1b0_0  
	importlib_resources       5.7.1              pyhd8ed1ab_0    conda-forge
	ipykernel                 6.13.0          py310hfdc917e_0    conda-forge
	ipython                   8.3.0           py310h06a4308_0  
	ipython_genutils          0.2.0              pyhd3eb1b0_1  
	ipywidgets                7.7.0              pyhd8ed1ab_0    conda-forge
	jedi                      0.18.1          py310h06a4308_1  
	jinja2                    3.1.2              pyhd8ed1ab_0    conda-forge
	json5                     0.9.6              pyhd3eb1b0_0  
	jsonschema                4.5.1              pyhd8ed1ab_0    conda-forge
	jupyter_client            7.3.0              pyhd8ed1ab_0    conda-forge
	jupyter_core              4.10.0          py310h06a4308_0  
	jupyter_server            1.17.0             pyhd8ed1ab_0    conda-forge
	jupyterlab                3.4.0              pyhd8ed1ab_0    conda-forge
	jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
	jupyterlab_server         2.13.0             pyhd8ed1ab_1    conda-forge
	jupyterlab_widgets        1.1.0              pyhd8ed1ab_0    conda-forge
	ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
	libffi                    3.4.2                h295c915_2  
	libgcc-ng                 11.2.0              h1d223b6_16    conda-forge
	libgomp                   11.2.0              h1d223b6_16    conda-forge
	libnsl                    2.0.0                h7f98852_0    conda-forge
	libsodium                 1.0.18               h7b6447c_0  
	libstdcxx-ng              11.2.0              he4da1e4_16    conda-forge
	libuuid                   2.32.1            h7f98852_1000    conda-forge
	libzlib                   1.2.11            h166bdaf_1014    conda-forge
	markupsafe                2.1.1           py310h5764c6d_1    conda-forge
	matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
	mistune                   0.8.4           py310h7f8727e_1000  
	nbclassic                 0.3.7              pyhd8ed1ab_0    conda-forge
	nbclient                  0.6.2              pyhd8ed1ab_0    conda-forge
	nbconvert                 6.5.0              pyhd8ed1ab_0    conda-forge
	nbconvert-core            6.5.0              pyhd8ed1ab_0    conda-forge
	nbconvert-pandoc          6.5.0              pyhd8ed1ab_0    conda-forge
	nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
	ncurses                   6.3                  h7f8727e_2  
	nest-asyncio              1.5.5           py310h06a4308_0  
	notebook                  6.4.11          py310h06a4308_0  
	notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge
	openssl                   3.0.3                h166bdaf_0    conda-forge
	packaging                 21.3               pyhd3eb1b0_0  
	pandoc                    2.18                 ha770c72_0    conda-forge
	pandocfilters             1.5.0              pyhd3eb1b0_0  
	parso                     0.8.3              pyhd3eb1b0_0  
	pexpect                   4.8.0              pyhd3eb1b0_3  
	pickleshare               0.7.5           pyhd3eb1b0_1003  
	pip                       22.0.4             pyhd8ed1ab_0    conda-forge
	prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
	prompt-toolkit            3.0.29             pyha770c72_0    conda-forge
	psutil                    5.9.0           py310h5764c6d_1    conda-forge
	ptyprocess                0.7.0              pyhd3eb1b0_2  
	pure_eval                 0.2.2              pyhd3eb1b0_0  
	pycparser                 2.21               pyhd3eb1b0_0  
	pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
	pyopenssl                 22.0.0             pyhd3eb1b0_0  
	pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
	pyrsistent                0.18.1          py310h5764c6d_1    conda-forge
	pysocks                   1.7.1           py310h06a4308_0  
	python                    3.10.4          h2660328_0_cpython    conda-forge
	python-dateutil           2.8.2              pyhd3eb1b0_0  
	python-fastjsonschema     2.15.3             pyhd8ed1ab_0    conda-forge
	python_abi                3.10                    2_cp310    conda-forge
	pytz                      2022.1             pyhd8ed1ab_0    conda-forge
	pyzmq                     22.3.0          py310h295c915_2  
	readline                  8.1.2                h7f8727e_1  
	requests                  2.27.1             pyhd3eb1b0_0  
	send2trash                1.8.0              pyhd3eb1b0_1  
	setuptools                62.1.0          py310hff52083_0    conda-forge
	six                       1.16.0             pyhd3eb1b0_1  
	sniffio                   1.2.0           py310h06a4308_1  
	soupsieve                 2.3.1              pyhd3eb1b0_0  
	sqlite                    3.38.5               h4ff8645_0    conda-forge
	stack_data                0.2.0              pyhd3eb1b0_0  
	terminado                 0.13.3          py310hff52083_1    conda-forge
	tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
	tk                        8.6.12               h27826a3_0    conda-forge
	tornado                   6.1             py310h7f8727e_0  
	traitlets                 5.1.1              pyhd3eb1b0_0  
	typing-extensions         4.2.0                hd8ed1ab_1    conda-forge
	typing_extensions         4.2.0              pyha770c72_1    conda-forge
	tzdata                    2022a                hda174b7_0  
	urllib3                   1.26.9          py310h06a4308_0  
	wcwidth                   0.2.5              pyhd3eb1b0_0  
	webencodings              0.5.1           py310h06a4308_1  
	websocket-client          1.3.2              pyhd8ed1ab_0    conda-forge
	wheel                     0.37.1             pyhd3eb1b0_0  
	widgetsnbextension        3.6.0           py310hff52083_0    conda-forge
	xz                        5.2.5                h7f8727e_1  
	zeromq                    4.3.4                h2531618_0  
	zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
	zlib                      1.2.11            h166bdaf_1014    conda-forge

conda env:
	name: ipywidgets_problem
	channels:
	  - defaults
	  - conda-forge
	dependencies:
	  - _libgcc_mutex=0.1=conda_forge
	  - _openmp_mutex=4.5=2_gnu
	  - anyio=3.5.0=py310h06a4308_0
	  - argon2-cffi=21.3.0=pyhd3eb1b0_0
	  - argon2-cffi-bindings=21.2.0=py310h7f8727e_0
	  - asttokens=2.0.5=pyhd3eb1b0_0
	  - attrs=21.4.0=pyhd3eb1b0_0
	  - babel=2.10.1=pyhd8ed1ab_0
	  - backcall=0.2.0=pyhd3eb1b0_0
	  - beautifulsoup4=4.11.1=py310h06a4308_0
	  - bleach=5.0.0=pyhd8ed1ab_0
	  - brotlipy=0.7.0=py310h7f8727e_1002
	  - bzip2=1.0.8=h7b6447c_0
	  - ca-certificates=2022.4.26=h06a4308_0
	  - certifi=2021.10.8=py310hff52083_2
	  - cffi=1.15.0=py310hd667e15_1
	  - charset-normalizer=2.0.12=pyhd8ed1ab_0
	  - cryptography=36.0.0=py310h9ce1e76_0
	  - debugpy=1.6.0=py310hd8f1fbe_0
	  - decorator=5.1.1=pyhd3eb1b0_0
	  - defusedxml=0.7.1=pyhd3eb1b0_0
	  - entrypoints=0.4=py310h06a4308_0
	  - executing=0.8.3=pyhd3eb1b0_0
	  - idna=3.3=pyhd3eb1b0_0
	  - importlib-metadata=4.11.3=py310h06a4308_0
	  - importlib_metadata=4.11.3=hd3eb1b0_0
	  - importlib_resources=5.7.1=pyhd8ed1ab_0
	  - ipykernel=6.13.0=py310hfdc917e_0
	  - ipython=8.3.0=py310h06a4308_0
	  - ipython_genutils=0.2.0=pyhd3eb1b0_1
	  - ipywidgets=7.7.0=pyhd8ed1ab_0
	  - jedi=0.18.1=py310h06a4308_1
	  - jinja2=3.1.2=pyhd8ed1ab_0
	  - json5=0.9.6=pyhd3eb1b0_0
	  - jsonschema=4.5.1=pyhd8ed1ab_0
	  - jupyter_client=7.3.0=pyhd8ed1ab_0
	  - jupyter_core=4.10.0=py310h06a4308_0
	  - jupyter_server=1.17.0=pyhd8ed1ab_0
	  - jupyterlab=3.4.0=pyhd8ed1ab_0
	  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
	  - jupyterlab_server=2.13.0=pyhd8ed1ab_1
	  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
	  - ld_impl_linux-64=2.36.1=hea4e1c9_2
	  - libffi=3.4.2=h295c915_2
	  - libgcc-ng=11.2.0=h1d223b6_16
	  - libgomp=11.2.0=h1d223b6_16
	  - libnsl=2.0.0=h7f98852_0
	  - libsodium=1.0.18=h7b6447c_0
	  - libstdcxx-ng=11.2.0=he4da1e4_16
	  - libuuid=2.32.1=h7f98852_1000
	  - libzlib=1.2.11=h166bdaf_1014
	  - markupsafe=2.1.1=py310h5764c6d_1
	  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
	  - mistune=0.8.4=py310h7f8727e_1000
	  - nbclassic=0.3.7=pyhd8ed1ab_0
	  - nbclient=0.6.2=pyhd8ed1ab_0
	  - nbconvert=6.5.0=pyhd8ed1ab_0
	  - nbconvert-core=6.5.0=pyhd8ed1ab_0
	  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
	  - nbformat=5.4.0=pyhd8ed1ab_0
	  - ncurses=6.3=h7f8727e_2
	  - nest-asyncio=1.5.5=py310h06a4308_0
	  - notebook=6.4.11=py310h06a4308_0
	  - notebook-shim=0.1.0=pyhd8ed1ab_0
	  - openssl=3.0.3=h166bdaf_0
	  - packaging=21.3=pyhd3eb1b0_0
	  - pandoc=2.18=ha770c72_0
	  - pandocfilters=1.5.0=pyhd3eb1b0_0
	  - parso=0.8.3=pyhd3eb1b0_0
	  - pexpect=4.8.0=pyhd3eb1b0_3
	  - pickleshare=0.7.5=pyhd3eb1b0_1003
	  - pip=22.0.4=pyhd8ed1ab_0
	  - prometheus_client=0.14.1=pyhd8ed1ab_0
	  - prompt-toolkit=3.0.29=pyha770c72_0
	  - psutil=5.9.0=py310h5764c6d_1
	  - ptyprocess=0.7.0=pyhd3eb1b0_2
	  - pure_eval=0.2.2=pyhd3eb1b0_0
	  - pycparser=2.21=pyhd3eb1b0_0
	  - pygments=2.12.0=pyhd8ed1ab_0
	  - pyopenssl=22.0.0=pyhd3eb1b0_0
	  - pyparsing=3.0.8=pyhd8ed1ab_0
	  - pyrsistent=0.18.1=py310h5764c6d_1
	  - pysocks=1.7.1=py310h06a4308_0
	  - python=3.10.4=h2660328_0_cpython
	  - python-dateutil=2.8.2=pyhd3eb1b0_0
	  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
	  - python_abi=3.10=2_cp310
	  - pytz=2022.1=pyhd8ed1ab_0
	  - pyzmq=22.3.0=py310h295c915_2
	  - readline=8.1.2=h7f8727e_1
	  - requests=2.27.1=pyhd3eb1b0_0
	  - send2trash=1.8.0=pyhd3eb1b0_1
	  - setuptools=62.1.0=py310hff52083_0
	  - six=1.16.0=pyhd3eb1b0_1
	  - sniffio=1.2.0=py310h06a4308_1
	  - soupsieve=2.3.1=pyhd3eb1b0_0
	  - sqlite=3.38.5=h4ff8645_0
	  - stack_data=0.2.0=pyhd3eb1b0_0
	  - terminado=0.13.3=py310hff52083_1
	  - tinycss2=1.1.1=pyhd8ed1ab_0
	  - tk=8.6.12=h27826a3_0
	  - tornado=6.1=py310h7f8727e_0
	  - traitlets=5.1.1=pyhd3eb1b0_0
	  - typing-extensions=4.2.0=hd8ed1ab_1
	  - typing_extensions=4.2.0=pyha770c72_1
	  - tzdata=2022a=hda174b7_0
	  - urllib3=1.26.9=py310h06a4308_0
	  - wcwidth=0.2.5=pyhd3eb1b0_0
	  - webencodings=0.5.1=py310h06a4308_1
	  - websocket-client=1.3.2=pyhd8ed1ab_0
	  - wheel=0.37.1=pyhd3eb1b0_0
	  - widgetsnbextension=3.6.0=py310hff52083_0
	  - xz=5.2.5=h7f8727e_1
	  - zeromq=4.3.4=h2531618_0
	  - zipp=3.8.0=pyhd8ed1ab_0
	  - zlib=1.2.11=h166bdaf_1014
	prefix: /home/luka/miniconda3/envs/ipywidgets_problem

</pre>
</details>

<details><summary>Installed Labextensions</summary>
<pre>
JupyterLab v3.4.0
/home/luka/miniconda3/envs/ipywidgets_problem/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        @jupyter-widgets/jupyterlab-manager v3.1.0 enabled OK (python, jupyterlab_widgets)
</pre>
</details>

**Comment by hpeiyan** [comment] 2022-05-16 08:52
same message

**Comment by martinRenou** [comment] 2022-05-16 08:58
The message is harmless and can be ignored for now.

If you don't see ipywidgets, it's unlikely to be the cause.

**Comment by jiangqucheng** [comment] 2022-05-25 06:27
same error, and the ipython interpreter doesn't working after this message.

**Comment by martinRenou** [comment] 2022-05-25 06:51
@jiangqucheng can you show your complete logs? I doubt this "error" is the cause of your issue, this is just a badly named warning.

**Comment by LukaPitamic** [comment] 2022-05-25 07:31
I can confirm in our case everything works as expected (we are running JLab in docker) thus we are ignoring the message. However, that kind of message gives me shivers - but as I understand we have what we have for now.
Keep on the good work work!

**Comment by andrix** [comment] 2022-05-26 15:54
I can confirm this same behavior. It does happen only when activating a Notebook, but not when browsing the files or doing other activity. 

```
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 025022db-6c07-4bde-8502-93ce5a59f2f3
```

Versions:
```
~ pip list | grep -E "(^jup|^ipy)"
ipykernel             6.13.0
ipython               8.3.0
ipython-genutils      0.2.0
ipywidgets            7.7.0
jupyter               1.0.0
jupyter-client        7.2.2
jupyter-console       6.4.3
jupyter-core          4.10.0
jupyter-dash          0.4.2
jupyter-server        1.16.0
jupyterlab            3.3.2
jupyterlab-pygments   0.2.2
jupyterlab-server     2.12.0
jupyterlab-widgets    1.1.0
```

Python: 
```python --version
Python 3.9.12
```

OS & Arch:
```
~ uname -a
Darwin ****** 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64
```

The result is I don't see any control when the widgets are missed:
![image](https://user-images.githubusercontent.com/283623/170525646-9666b33a-9b44-4d82-95b7-e27f5a4f0486.png)

**Comment by Koesters** [comment] 2022-05-31 10:37
Same here 

```
ipykernel            6.13.0
ipython              8.4.0
ipython-genutils     0.2.0
ipywidgets           7.7.0
jupyter              1.0.0
jupyter-client       7.3.1
jupyter-console      6.4.3
jupyter-core         4.10.0
jupyterlab-pygments  0.2.2
jupyterlab-widgets   1.1.0
```

`Python 3.9.2`

`5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux`

**Comment by utkonos** [comment] 2022-06-09 02:26
This is a duplicate of an older issue:

https://github.com/jupyter-widgets/ipywidgets/issues/2257

I'm just linking these two issues b/c I can see the error still exists. I searched for the error looking to see if there was an update, but I didn't see that other issue in the search results. That issue has a complete explanation as to what is going on and why this error and warning can be ignored.

**Comment by jasongrout** [comment] 2022-06-09 03:48
Thanks for the reference. In particular, these two comments are where the explanation is: https://github.com/jupyter-widgets/ipywidgets/issues/2257#issuecomment-1110226272

**Closed by jasongrout** 2022-06-09 03:48 UTC
Labels: resolved-locked, answered

**Comment by LukaPitamic** [comment] 2022-06-09 07:11
@jasongrout thank you, we can all sleep better now ;)

**Comment by eabase** [comment] 2022-06-22 15:50
From the link above: 
> ...when using a Python virtual environment, the custom ipykernel must be re-built and all packages installed so it can (somehow) take all Jupyter extensions into account and not incur into this kernel comm ERROR and WARNING. In other words re-building the custom ipykernel solves the issue by making the kernel aware of necessary comm target(s)...

> This should be considered as an informational log message...

**Comment by irealmatin** [comment] 2022-09-04 08:44
https://discourse.jupyter.org/t/ipkernelapp-error-and-warning/13820
this can help

**Comment by utkonos** [comment] 2022-09-04 15:15
@irealmatin 

I did a fresh install a few days ago, but this problem still exists. There isn't a solution yet, but my recommendation is to wait patiently for a fix. It is a harmless error according to everything that has been posted in any of the issues or forum posts related to it.

Here is the current state:
https://github.com/jupyter-widgets/ipywidgets/issues/2257#issuecomment-1230974836

**Comment by joshy** [comment] 2023-03-31 15:33
I had the same problem but restarting the systemd service resolved it for me. I am running jupyer lab via systemd and installed ipywidgets into the virtual environment. Kernel restarts didn't worked for me and also ipywidgets interactive was broken. A restart of the service solved it for me. Maybe it helps other people.
