### ISSUE TITLE
Creating new Widgets based on the Multiple Selection!

### ISSUE THREAD

**Issue by moradza** [jupyter-widgets/ipywidgets#2547] opened 2019-09-04 00:18 UTC
I have a multiple selections widget, each time the user selects new options from the MultipleSelection widget, I want to display new floatslider widgets with the  selected options.

Is it possible?

Thanks,

**Comment by pbugnion** [comment] 2020-01-08 14:06
Unless I'm mistaken, this is a duplicate of #2551. I'm closing this one, but feel free to re-open if you think it's a distinct issue.

**Closed by pbugnion** 2020-01-08 14:06 UTC
