### ISSUE TITLE
TraitError suppressed by observe might be unexpected?

### ISSUE THREAD

**Issue by johnnychen94** [jupyter-widgets/ipywidgets#2317] opened 2019-02-15 12:58 UTC
I'm new to `ipywidget`, while I'm playing with these widgets I find this behavior not satisfying: 

:) It raises a `TraitError` if 
```python
caption = widgets.Label()
caption.value = 1 # TraintError
```

:( However, in the following example with `observe` this error is suppressed, and `slider_value.value` failed to update _without any warning/info_.

```python
slider = widgets.IntSlider()
slider_value = widgets.Label(value="value of the slider")

def on_value_change(change):
  slider_value.value = change['new'] # to make it work we need `str(change['new'])`

slider.observe(on_value_change, names='value')
display(slider_value, slider)
```

**Comment by krey** [comment] 2019-02-15 14:17
Does this help?
https://ipywidgets.readthedocs.io/en/stable/examples/Output%20Widget.html#Debugging-errors-in-callbacks-with-the-output-widget

**Comment by johnnychen94** [comment] 2019-02-15 23:40
yes this helps, after running
```python
slider = widgets.IntSlider()
slider_value = widgets.Label(value="value of the slider")

debug_view = widgets.Output(layout={'border': '1px solid black'})

@debug_view.capture(clear_output=True)
def on_value_change(change):
  slider_value.value = change['new'] # to make it work we need `str(change['new'])`

slider.observe(on_value_change, names='value')
display(slider_value, slider)
```
then `display(debug_view)` will output the `TraitError` raised by `on_value_change`.

I was just not understanding the mechanism here and thought it's suppressed by mistake.

**Comment by jasongrout** [comment] 2019-02-20 16:09
It's operating as designed. The issue is that there is not a good mechanism right now in Jupyter for associating an output area for such an error to be displayed. There is more discussion at https://github.com/jupyterlab/jupyterlab/issues/1254, along with some future things we can explore to make this work better for users.

**Comment by jasongrout** [comment] 2019-05-05 05:11
Closing as answered.

**Closed by jasongrout** 2019-05-05 05:11 UTC
