### ISSUE TITLE
Shift + left click can not select in range properly in widgets.SelectMultiple

### ISSUE THREAD

**Issue by Thenorthernsea** [jupyter-widgets/ipywidgets#3615] opened 2022-10-21 02:20 UTC
Test code:
![image](https://user-images.githubusercontent.com/46848128/197096016-8dde154f-55a2-4dd5-819c-7d7ee830a611.png)
can not select a range using shift + left click,
but if I make the description selected I will be able to select in range:
![image](https://user-images.githubusercontent.com/46848128/197096101-5cf72dd8-a52f-4339-92a0-6d87995a46ad.png)

**Comment by Thenorthernsea** [comment] 2022-10-21 02:20
Only shift + mouse click left is affected

**Comment by jasongrout** [comment] 2022-10-21 03:20
Confirmed on current macOS Monterey with both Chrome and Firefox, and with both ipywidgets 7 and 8. In fact, if I highlight any text anywhere in the browser window, the shift-click starts working.

**Comment by jasongrout** [comment] 2022-10-21 04:19
This seems to be a bug in JupyterLab, as it works fine in Jupyter Notebook. I think JupyterLab is trapping the shift-click events, as they aren't even reaching the select box.

**Comment by jasongrout** [comment] 2022-10-21 05:31
My guess is that this line in JupyterLab is responsible, as it prevents the browser default behavior, but only if no text is selected: https://github.com/jupyterlab/jupyterlab/blob/26999c5df85dd8a088580b5dafbc5404ef9b4a44/packages/notebook/src/widget.ts#L2140

**Comment by Thenorthernsea** [comment] 2022-11-20 08:58
Thanks for your help to look into this! @jasongrout

**Comment by jasongrout** [comment] 2022-11-22 18:28
Thanks. We'll close this issue since it is now opened in JupyterLab.

**Closed** 2022-11-23 14:47 UTC
Labels: resolved-locked
