### ISSUE TITLE
7.0.0: Cannot load notebook with saved widget output

### ISSUE THREAD

**Issue by ak0ska** [jupyter-widgets/ipywidgets#1667] opened 2017-08-21 15:26 UTC
Hello,

We have a problem with the new version of ipywidgets (or more likely with the widgetsnbextension), where a notebook with a saved widget output cannot be loaded.

When loading such a notebook the following error message is thrown in the browser (Firefox):

```
Notebook failed to load

The error was:
TypeError: Jupyter.notebook.kernel is null

See the error console for details.
```

It occurs in widgetsnbextension's [render](https://github.com/jupyter-widgets/ipywidgets/blob/master/widgetsnbextension/src/extension.js#L105) function. It seems as if the kernel was not yet ready when the widget manager property is accessed.

We have the following library versions for Python2 and Python3 respectively:
``` console
root@de79f18a1f6a:~# pip2 show ipython notebook nbformat ipywidgets widgetsnbextension traitlets | grep Version -B1
Name: ipython
Version: 5.4.1
--
Name: notebook
Version: 5.0.0
--
Name: nbformat
Version: 4.3.0
--
Name: ipywidgets
Version: 7.0.0
--
Name: widgetsnbextension
Version: 3.0.0
--
Name: traitlets
Version: 4.3.2


root@de79f18a1f6a:~# pip3 show ipython notebook nbformat ipywidgets widgetsnbextension traitlets | grep Version -B1
Name: ipython
Version: 6.1.0
--
Name: notebook
Version: 5.0.0
--
Name: nbformat
Version: 4.3.0
--
Name: ipywidgets
Version: 7.0.0
--
Name: widgetsnbextension
Version: 3.0.0
--
Name: traitlets
Version: 4.3.2
```

We use Python2 kernels for our notebooks, and here is an example notebook with which we can reproduce the problem: https://gist.github.com/ak0ska/efd644222cbbe936c822f941c3e708fa

If I clear all output, save and reload the notebook, there is no error message. If I execute all cells, save the notebook and reload, I get the error message. The example works without problems with ipywdgets 6 and widgetsnbextension 2.

Any ideas what might be wrong?

Thank you,
Akos

**Comment by jasongrout** [comment] 2017-08-21 16:00
> It seems as if the kernel was not yet ready when the widget manager property is accessed.

Interesting, thanks for the report. I'm really curious why the renderer is being run before the kernel is ready. I'm trying to reproduce this.

Is it a consistent error message, or does it just happen sometimes? Does your kernel take a long time to start?

**Comment by ak0ska** [comment] 2017-08-21 16:11
Hi Jason,

The error is consistent. As for the kernel load times I don't have any exact figures, but it doesn't feel long. When the error message pops up, shortly after I can see the "Kernel ready" label appearing in the notebook status bar.

Hope you can reproduce the issue. ;)

Thanks,
Akos

**Comment by jasongrout** [comment] 2017-08-21 16:18
I can't reproduce this (at least in the first time I tried). Can we hop on a video conference to debug this on your computer? We could use https://appear.in/ipywidgets

**Comment by jasongrout** [comment] 2017-08-21 16:23
(we can make an easy check, but then the widgets won't be rendered, so I'd like to see why the rendering is happening apparently before the kernel is being constructed.)

**Comment by pbugnion** [comment] 2017-08-21 16:25
I get the same behaviour when I try to load a notebooks that contains widgets created with ipywidgets 6.x. I made it go away by clearing the output.

**Comment by pbugnion** [comment] 2017-08-21 16:26
Apologies -- I closed this by accident.

**Comment by jasongrout** [comment] 2017-08-21 16:27
oh, interesting. ipywidgets 6? I'll try that, but it sounds like the problem above may be different, i.e., we start with the notebook given above, and *then* save state and reload (all with widgets 7) - right @ak0ska?

**Comment by pbugnion** [comment] 2017-08-21 16:33
Yes -- if I opened an existing notebook that had widgets created with ipywidgets 6, I would sometimes (though not consistently) get the error mentioned. This went away when I cleared the widget state.

It does seem to be a different problem, though.

**Comment by jasongrout** [comment] 2017-08-21 16:38
Did the error point to the same line (the one in the renderer assuming the existence of `Jupyter.notebook.kernel`)?

**Comment by ak0ska** [comment] 2017-08-21 18:10
The notebook in the gist was originally created in an environment that uses ipywidgets 5.2.2, but looking at the raw notebook JSON, the nb format is 4.1, so I thought it should be working. 

We are preparing to upgrade our docker image used by Jupyterhub, and we have a large volume of notebooks that will be coming from that environment. What I did is I created a new notebook in our current production environtment (ipywidgets 5.2.2), saved it without output, then opened this notebook in our new test environment (with up to date Jupyter stack), executed the cells, saved, and reloaded. The gist above is the result after saving the notebook.

In any case, tomorrow I can try to create a pristine notebook with ipywidgets 7 and see if it is different. I will also try clearing the widget state. We can even do a video conference, though I live in the CET timezone, not sure if that's a problem.

Thanks,
Akos

**Comment by pbugnion** [comment] 2017-08-21 18:36
I'm struggling to reproduce this again -- I should have made a note of it, sorry.

**Comment by jasongrout** [comment] 2017-08-21 19:21
> We are preparing to upgrade our docker image used by Jupyterhub, and we have a large volume of notebooks that will be coming from that environment. What I did is I created a new notebook in our current production environtment (ipywidgets 5.2.2), saved it without output, then opened this notebook in our new test environment (with up to date Jupyter stack), executed the cells, saved, and reloaded. The gist above is the result after saving the notebook.

At what point did you see the error?

**Comment by ak0ska** [comment] 2017-08-22 09:28
When loading the notebook with the saved widget output. If I load the notebook with the output cleared, it's good. I made a [video](https://youtu.be/YKCeCL7Nrtw) of it. In the console you can see that the kernel is created after the exception.

**Comment by jasongrout** [comment] 2017-08-22 12:31
Thanks, that log does indeed indicate the kernel was created after the exception. As a stopgap, let's merge and release 7.0.1 with #1668, and then after JupyterCon I can try to do a little more digging about why the kernel is started after the rendering.

if the rendering is supposed to be able to happen before the kernel is started, then we can refactor the widget manager to not expect a kernel at initialization, and be able to set the kernel after startup.

**Comment by jasongrout** [comment] 2017-08-22 12:44
If you can install from pip, can you try upgrading to widgetsnbextension 3.0.1 and see if that at least lets you open the notebook now? It won't render the widgets, but it shouldn't throw that error anymore.

**Comment by ak0ska** [comment] 2017-08-23 09:15
Sorry for my late reply, I tested with 3.0.1 and it's not preventing the error:

```
Notebook failed to load from JSON: TypeError: manager is null
Stack trace:
render@https://[..]/jupyterhub/user/300120/nbextensions/jupyter-js-widgets/extension.js?v=20170823110430:62105:13
[..]
```

It happens on [this line](https://github.com/jupyter-widgets/ipywidgets/blob/master/widgetsnbextension/src/extension.js#L111). Above you test manager for `undefined`, but according to this error message it's `null`.

**Closed** 2017-08-24 03:09 UTC

**Comment by jasongrout** [comment] 2017-08-24 03:24
Can you try the widgetsnbextension 3.0.2 I just pushed to pypi?

**Comment by ak0ska** [comment] 2017-08-24 09:13
It now displays the error message `Error rendering Jupyter widget. Widget not found: {"model_id":"f520c73d1d9d43d8977b3347a26b0b89","version_minor":0,"version_major":2}` in place of the widget, and the previous exception is gone. Thanks!

**Comment by michaelaye** [comment] 2017-08-27 19:05
The update to 3.0.2 also solved this error for me (using Chrome on OSX 10.12.6):

![screenshot 2017-08-27 12 57 38](https://user-images.githubusercontent.com/69774/29753152-58e5ae6c-8b28-11e7-9a95-7c6a365ba7b0.png)

![screenshot 2017-08-27 12 58 20](https://user-images.githubusercontent.com/69774/29753150-539559f8-8b28-11e7-9108-cfc583c5a2f9.png)

**Comment by jonathansp** [comment] 2017-09-12 20:27
It's easy to reproduce:

1. Create a new notebook.
2. Execute the follow snippet:
```
import IPython
import ipywidgets

html = ipywidgets.HTML('<h1>Title</h1>')
IPython.display.display(html)``` 

You'll see **Title**.

3.Go to File > Save and Checkpoint.
4. Go to File > Close and Halt.
5. Open the same notebook again. You gonna see:

![screen shot 2017-09-12 at 17 26 15](https://user-images.githubusercontent.com/457972/30346573-97817bd8-97df-11e7-94d1-a3fb5365b199.png)

**Comment by jasongrout** [comment] 2017-09-13 01:21
The error in this issue was solved (and had to do with a javascript error after saving the widget state explicitly via the Widget menu). What you are seeing is the expected behavior for the steps you did under the current design. Since you stopped the kernel, and didn't save the widget state explicitly (from the Widgets menu), the widget data is not around to be displayed, hence the error.

Always glad to improve things, though. What did you expect to happen?

**Comment by jonathansp** [comment] 2017-09-13 15:03
Indeed it is different from the original error reported in this issue. Thank you @jasongrout for clarifying it. However, this message conveys the idea of something is going wrong. It is my understanding that Jupyter was trying to say "the state of this widget was not found" or maybe "the instance of the widget was not found", but not the _widget_ itself.

Perhaps, the simplest solution would be to change the message. It is more like a warning than an error. Also, I've thought about two more approaches that could work, but I haven't got a chance to check out the code yet.

1. Give the users a simple way to reload the widget, or ask them for running the cell again.

![screen shot 2017-09-13 at 11 57 31](https://user-images.githubusercontent.com/457972/30384476-c26cd2d4-987a-11e7-803e-ef3f305550fc.png)

2. Optionally, autosave widgets' state when notebook sets a checkpoint. 

![screen shot 2017-09-13 at 11 47 17](https://user-images.githubusercontent.com/457972/30384375-809d68e6-987a-11e7-9489-122a37ea64de.png)

**Comment by jasongrout** [comment] 2017-09-15 02:53
That makes a lot of sense to change the message to be clearer that it isn't a fatal error, but the cell just needs to be executed to see the widget. 

> Give the users a simple way to reload the widget, or ask them for running the cell again.

They can't reload the widget since the state doesn't exist anywhere. Running the cell may work, or it may not - it may be that they need to run the entire notebook up to that point, or run some other cells. However, I like the idea of helping the user to know what to try next.

We don't want to automatically save the widget state (we used to, and it was a mess, significantly bloating notebook files and constantly churning their outputs).

Before pursuing this further, would you open a new issue and copy your comment above to it? Let's track the discussion on a new issue dedicated to this.

**Comment by Caelin1234** [comment] 2020-05-07 16:21
I am having this widget error and am new to jupyter has it been resolved? I do not see new error message for the widget. 
My error is: 
"A Jupyter widget could not be displayed because the widget state could not be found. This could happen if the kernel storing the widget is no longer available, or if the widget state was not saved in the notebook. You may be able to create the widget by running the appropriate cells."

re running cells, re starting kernal and run all, and creating a new script did not solve this.

**Comment by jasongrout** [comment] 2020-05-07 16:54
@Caelin1234 - what versions of the notebook/lab and ipywidgets do you have installed? What widgets are you using? Can you post a simplified example just using core ipywidgets (sliders, text boxes, etc.) illustrating the issue?
