### ISSUE TITLE
Button crashes on input

### ISSUE THREAD

**Issue by ghost** [jupyter-widgets/ipywidgets#44] opened 2015-06-10 06:14 UTC
Take a look at this [notebook](http://nbviewer.ipython.org/urls/gist.githubusercontent.com/sumitsahrawat/8a68f4927e39d16f1b67/raw/1af1579d3d0f2aa75f16e56289529c249bbfbaa2/Button%20Input.ipynb).

EDIT: Updated notebook to show error on nbviewer.

**Comment by SylvainCorlay** [comment] 2015-07-14 15:08
You should rather use `raw_input`, `input` is like `eval`.

**Comment by sumitsahrawat** [comment] 2015-07-15 20:31
@SylvainCorlay Replacing `input` with `raw_input` didn't work. Was that what you meant?

**Python 2** (same error)

```
EOFError: EOF when reading a line
```

**Python 3**

```
NameError: name 'raw_input' is not defined
```

I found out ([SO](http://stackoverflow.com/a/954840/2388535)) that python 3 renamed `raw_input` to `input`.

**Comment by SylvainCorlay** [comment] 2015-07-16 13:05
In Python 2, input will execute whatever you typed. For example, if you type only `?`, you will get that error, and not if you typed `"?"`...

**Comment by sumitsahrawat** [comment] 2015-07-23 13:13
I think the error occurs because `input_request` can only be sent in response to an `execute_request`. Sending `input_request` in response to `comm_data` doesn't give the frontend a chance to create a text widget for input, and an `EOF` is sent instead.

A possible solution would be to have the widget manager take care of `input_request` messages sent in the form of `comm_data` messages, similar to how the output widget uses `display_data` and `clear_output`.

**Comment by jdfreder** [comment] 2015-10-15 18:48
I know it's been a while, sorry, but I'm looking into this now.  Unfortunately it's not as simple as adding another handler to the callback dict.  There's something wrong with the way code is being executed in the kernel as a response from a comm message, which is preventing it from being able hook `raw_input` and `input`.  It's unclear to me where the context difference actually is taking place.

**Comment by jdfreder** [comment] 2015-10-15 19:13
Ok, looks like this is caused by a fundamental difference in the way code triggered by cell execution is ran vs in response to a comm message.  The `do_execute` function of `ipykernel.py` in `ipython/kernel` sets the stage for input requests.  However, simply calling `get_ipython().kernel.self._forward_input()` does **not** solve the problem.

This is related to the longggggg standing issue posted here: https://github.com/ipython/ipython/issues/4983

**Comment by jdfreder** [comment] 2015-10-15 19:19
Honestly, I'm not sure how to fix this properly.  I think we need to move all of the context setting machinery into a context manager, or something, that can be used without the do_execute function.  Then, that context could be applied to comm message handlers.

Apparently I shouldn't have closed https://github.com/ipython/ipython/issues/5006 .

**Comment by jasongrout** [comment] 2016-11-11 14:28
The example code is:

```python
from IPython.html.widgets import *
b = Button()
b.description = "!! Click Me !!"
def fun(t):
    s = input("Enter something: ")
    print(s)

b.on_click(fun)
b
```

**Comment by jasongrout** [comment] 2016-11-11 16:26
At this point: It looks like the example code above does not produce an input in JupyterLab.

**Comment by jasongrout** [comment] 2016-11-14 21:50
Looking at this a bit more - both the notebook and JLab properly ask for inputs when doing something like:

```
def f():
    return input('> ')
```

However, neither ask for input on a button click like above, and looking at the messages, the notebook doesn't even get the stdin message. Given Jon's statements about work involved, I'm moving this to a feature request after 6.x (likely it will actually be a PR to the ipykernel repo).

**Comment by jasongrout** [comment] 2016-11-17 05:21
Closed in deference to https://github.com/jupyterlab/jupyterlab/issues/1254

**Closed by jasongrout** 2016-11-17 05:21 UTC
Labels: bug, resolved-locked

**Comment by wwells-apixio** [comment] 2022-02-02 00:51
Was this ever resolved? Doesn't look like it...

`from IPython.html.widgets import *
b = Button()
b.description = "!! Click Me !!"
def fun(t):
    s = input("Enter something: ")
    print(s)

b.on_click(fun)
b`
This still throws errors.
In fact, this seems to be the underlying reason why pdb does not work inside the handler callback.

**Comment by jasongrout** [comment] 2022-02-02 02:27
Updated code example for JupyterLab:

```python
from ipywidgets import *
b = Button()
b.description = "!! Click Me !!"
@out.capture()
def fun(t):
    s = input("Enter something: ")
    print(s)

b.on_click(fun)
display(b)
display(out)
```
And yes, it does seem like `input()` is still not supported.
