### ISSUE TITLE
Button icons vs. FontAwesome version

### ISSUE THREAD

**Issue by kebwi** [jupyter-widgets/ipywidgets#2557] opened 2019-09-11 18:03 UTC
I discovered that lots of potential icons don't appear when used in ipywidgets. Some investigating suggests that Jupyter notebook and/or ipywidgets are relying on older versions of FontAwesome.

How do I see what version of FontAwesome Jupyter and/or ipywidgets is using?

How do I see the local filepath to where ipywidgets is being retrieved?

Is it possible to manually install a more recent version of FontAwesome and point Jupyter/ipywidgets at that other location in order to gain access to icons that are not supported by the default installation? If it matters, one of my systems is running Jupyter from Anaconda and another I'm not sure of its installation/management method.

I'd love to get access to more recent icon sets in my ipywidget interfaces. Thanks.

As I commented on another issue, I'd also love to attach multiple icons to a button. As I understand it, this behavior was once supported and was explicitly removed for some reason.

**Comment by kebwi** [comment] 2019-09-17 17:03
Thank you in advance. I'm onboard with the *idea* of becoming a contributor, but I'm not sure I have time to ramp up right now. Usual life/work distractions.

**Comment by martinRenou** [comment] 2020-01-08 10:37
Duplicate of https://github.com/jupyter-widgets/ipywidgets/issues/2217

**Closed by martinRenou** 2020-01-08 10:37 UTC
