### ISSUE TITLE
Binder not working

### ISSUE THREAD

**Issue by WesleyTheGeolien** [jupyter-widgets/ipywidgets#2301] opened 2019-01-21 22:59 UTC
Hello,

I have just tried out the binder associated with this repository and unfortunately, the notebooks cannot be rerun. 

From my understanding of the Binder project, it looks in the repository for a `requirements.txt` which is not present leading to the python environment inside the docker container being non-usable. Is there a way to override this?

As a fix maybe adding the requirements needed would be a solution but I also realise that this repository is a library for the ipywidgets and that the requirements needed to run the notebooks are not necessarily the same as the requirements needed to for the package. If the former is chosen I would be happy to look through the notebooks and write the `requirements.txt`

**Comment by mgeier** [comment] 2020-01-05 09:38
I've created #2659, but sadly, it doesn't work yet. If you have an idea how to fix it, please chime in!

**Comment by pbugnion** [comment] 2020-01-07 13:23
Hi both! Thanks for raising this.

I can't reproduce the issue you mention. The binder link works fine for me, at least in the classic notebook:

<img width="1226" alt="Screenshot 2020-01-07 at 13 21 16" src="https://user-images.githubusercontent.com/1392879/71898165-8662fb80-3150-11ea-8fb3-63a380d6c10b.png">

The binder URL ends with query string `filepath=/docs/source/examples`, which does have a `requirements.txt`.

JupyterLab doesn't work because it is missing the JupyterLab extension.

I'm going to close this, but feel free to re-open if you think I'm wrong.

**Closed by pbugnion** 2020-01-07 13:23 UTC

**Comment by WesleyTheGeolien** [comment] 2020-01-09 10:42
Thanks @pbugnion, the Binder now seems to be working however most of the default tutorials use libraries that are nto installed (numpy, matplotlib, leaflet) would it be forseeable to install these using an option in the setup.py say requirements-demo.txt

I'd be more than happy to do the work.

**Comment by mgeier** [comment] 2020-01-09 11:33
> I'd be more than happy to do the work.

I've already started the work in #2659 and #2701.
Both contain the necessary dependencies.
But both have problems installing the correct version of the widgets for JupyterLab.

If you have any ideas how to proceed there, that would be great!

**Comment by mgeier** [comment] 2020-01-09 14:51
FYI: now #2701 works.
