### ISSUE TITLE
ipyaggrid inside Accordion - columns do not resize

### ISSUE THREAD

**Issue by SujPer** [jupyter-widgets/ipywidgets#2858] opened 2020-04-30 17:23 UTC
Hello,

Adding an ipyaggrid as a child into an accordion, if that level of the accordion is closed when displayed, when you expand that level, you will note that the columns of the ipyaggrid have not properly rendered. I know this is not an issue with ipyaggrid as if i display the grid outside of the accordion it renders correct. Also, strangely, if the ipyaggrid is on in the first level of the accordion (which displays on loading), the rendering works. It seems that the column rendering is not run on the opening of a level, even if you pass the parameter columns_fit="auto" when creating the grid

**Comment by jasongrout** [comment] 2020-04-30 18:03
There should be a signal sent to child widgets letting them know when they are hidden or displayed. Either there is an issue with this signal being sent, or there is an issue with ipyaggrid in listening to this signal and appropriately resizing itself. Can you post a clear reproducible example?

**Comment by SujPer** [comment] 2020-04-30 18:25
Hello, please see below. I have creates a 2 level accordion and placed the grid in the second level (which is collapsed on loading). You will note that the cols havent rendered. If you switch the grid to level 1 of the accordion and rerun, you will see that the columns do render, because level one is not collapsed on loaded. Is there a parameter to pass into accordion to ensure non of the levels are collapsed on loading? 

from ipywidgets.widgets import Label, Accordion
from ipyaggrid import Grid


cols = ['Name','Age','Height', 'Weight']
data = [['Ant',25,6,76],['Ben',25,5,82],['Tim',32,5,85],['Tim',31,5,43],['Jon',32,5,85] ]
test_df = pd.DataFrame(data, columns=cols)

#### COMPONENT 1 FOR ACCORDION ####
test_label = Label('TESTING')

#### COMPONENT 2 FOR ACCORDION ####
column_defs = [{'field': c} for c in cols]

grid_options = {
    'columnDefs' : column_defs,
    'enableColResize': True,
    'enableRangeSelection': True,
    'suppressColumnVirtualisation': True  #this flag should allow column resizing when hidden
}

test_grid = Grid(grid_data=test_df,
         width="100%",
         grid_options=grid_options,
         index=False,
         columns_fit="auto"
        )

#### ACCORDION ####
accordion = Accordion(children=[test_label, test_grid ])
accordion.set_title(0, 'LEVEL_1')
accordion.set_title(1, 'LEVEL_2')
accordion

**Comment by jasongrout** [comment] 2020-04-30 18:51
> Is there a parameter to pass into accordion to ensure non of the levels are collapsed on loading?

No, only one area is visible at a time in an accordion.

Also, did you try asking the ipyaggrid project? My guess is that this is an ipyaggrid issue not listening to the signals that are provided by ipywidgets.

**Comment by jasongrout** [comment] 2020-04-30 18:55
My guess is that ipyaggrid will need to do something like what we had to do in bqplot to layout things when they became visible: https://github.com/bqplot/bqplot/pull/1047

**Comment by jasongrout** [comment] 2020-04-30 18:56
My guess is that you'll also see these problems using tabs, if ipyaggrid is assuming that it is visible and laying itself out when it is added to the page.

**Comment by jasongrout** [comment] 2020-04-30 19:01
I reproduced the issue, and with tabs as well. I think this is an ipyaggrid issue, probably similar to the bqplot issue we solved at bqplot/bqplot#1047. Can you file an issue with ipyaggrid?

**Comment by jasongrout** [comment] 2020-04-30 19:02
Closing since this appears to be an issue with ipyaggrid - feel free to keep discussing if you feel this is an issue with ipywidgets core instead, of course.

**Closed by jasongrout** 2020-04-30 19:01 UTC

**Comment by SujPer** [comment] 2020-05-01 07:03
Hello, One more question on this please. Do you exposure the event uncollapsing event? If so, would you kindly share an example of this so i can force a rendering on the grid object from that.

Thanks,

**Comment by jasongrout** [comment] 2020-05-01 07:10
On the python side, you'll see the `selected_index` attribute change when a new section is opened (i.e., "selected"). However, this refresh problem should really be handled by ipyaggrid totally on the javascript side, similar to how we do things in bqplot.

**Comment by SujPer** [comment] 2020-05-01 07:17
Thanks Jason. I have raised this with them but need a quick fix. So to confirm I shall implement "accordion.observe(<my_method>)", and in my method check the value of selected_index?

**Comment by jasongrout** [comment] 2020-05-01 07:20
I think you can observe the selected_index attribute specifically: `accordion.observe(my_method, 'selected_index')`

**Comment by SujPer** [comment] 2020-05-01 07:54
Thanks for your help James, its much appreciated.
