### ISSUE TITLE
documentation on readthedocs fails to show rendered LaTeX

### ISSUE THREAD

**Issue by parmentelat** [jupyter-widgets/ipywidgets#1267] opened 2017-04-07 08:12 UTC
I would have expected the captions on the attached screenshot to be rendered as equations

![screen shot 2017-04-07 at 10 09 40](https://cloud.githubusercontent.com/assets/4519227/24791448/698a44e4-1b7a-11e7-8831-07d5acce5010.png)

**Comment by jasongrout** [comment] 2017-04-08 01:25
@SylvainCorlay - do you know what is going on there?

**Comment by SylvainCorlay** [comment] 2017-04-08 01:31
Nope, but it seems specific to RTD. The problem does not occur on nbviewer: http://nbviewer.jupyter.org/github/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20Styling.ipynb

**Comment by SylvainCorlay** [comment] 2017-04-08 01:37
MathJax is loaded on the page and typeset is called correctly

**Comment by jasongrout** [comment] 2017-04-08 02:44
By the way, here is the link for the original issue: http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Styling.html#Latex

**Comment by jasongrout** [comment] 2017-04-08 03:00
Looks to me like the issue is that RTD mathjax is configured with the default tex inline delimiters `\(` and `\)`, while the notebook and nbviewer also have `$`. We should either change our example in the docs to `\(` and `\)`, or fix our theme in RTD.

**Comment by jasongrout** [comment] 2017-04-20 12:53
> fix our theme in RTD.

(Preferably this, since there are many notebooks that have `$` delimiters)

**Comment by jasongrout** [comment] 2017-05-18 22:08
This should be fixed in #1363 - we'll wait until rtd updates to make sure.

**Comment by jasongrout** [comment] 2017-05-19 18:07
It appears that `$x^2$` is still not recognized, but `$$x^2$$` is. We'll need to fix that in the jupyter-alabaster theme, maybe.

**Comment by jasongrout** [comment] 2017-05-19 18:34
Actually, it looks like it's a setting in the mathjax sphinx extension, but not documented: https://github.com/sphinx-doc/sphinx/blob/0008d576fc82e196c8b7d3c82b7718ffb11b605d/sphinx/ext/mathjax.py#L79

**Comment by jasongrout** [comment] 2017-05-19 20:33
Never mind, that config option seems to be for math written in the docs (it wraps with those delimiters), not for configuring mathjax. It seems like there's not a way to adjust the mathjax config easily, so I'll just change the actual docs themselves.

**Closed** 2017-05-19 21:12 UTC
Labels: docs
