### ISSUE TITLE
Error Installing @jupyter-widgets/jupyterlab-manager@3.0.1

### ISSUE THREAD

**Issue by jhamet93** [jupyter-widgets/ipywidgets#3307] opened 2021-11-04 11:17 UTC
## Description

ValueError: "@jupyter-widgets/jupyterlab-manager@3.0.1" is not a valid extension:
schemaDir is empty: "./schema"

## Reproduce

`jupyter labextension install @jupyter-widgets/jupyterlab-manager@3.0.1` within the latest JupyterLab3 environment

## Expected behavior

Lab extension successfully installs

## Context

Attempting to upgrade company JupyterLab offering to 3.X so bumping this installation

**Comment by jtpio** [comment] 2021-11-04 13:03
Thanks @jhamet93 for reporting this issue :+1: 

I could reproduce it locally in a new environment with:

```
mamba create -n tmp python=3.9 jupyterlab=3 -y
conda activate tmp
jupyter labextension install @jupyter-widgets/jupyterlab-manager@3.0.1
```

The `schema` seems to be correctly bundled in the source extension. So maybe it's an issue with the `jupyter labextension install` command and the handling of schemas.

> Attempting to upgrade company JupyterLab offering to 3.X so bumping this installation

Normally this command is not stricly necessary with JupyterLab 3.0. Installing `ipywidgets>=7.5` in the same environment as JupyterLab should also install the `@jupyter-widgets/jupyterlab-manager` extension automatically, using the prebuilt extension system added in JupyterLab 3.0.

Would you be able to check whether this fixes the issue?

**Comment by jhamet93** [comment] 2021-11-09 14:35
I was able to fix the issue using as you stated but in a slightly hacky manner. At Twitter, we use pexes to conceal our Python environment which means exposing the contents of this pex a bit hacky in order for the prebuilt extension system to discover the correct location.

Is still being able to install this extension via `jupyter labextension install` for 3.X an expected behavior ? If so, I'm happy to follow along an issue or introduce a possible pull request to resolve this.

**Comment by jtpio** [comment] 2021-11-09 15:49
> Is still being able to install this extension via `jupyter labextension install` for 3.X an expected behavior ?

Yes this is still supported.

It looks it is hitting that line in the extension manager code in JupyterLab: https://github.com/jupyterlab/jupyterlab/blob/2b8a2cedcdb7cd4d3aac556692b146e8712a0e8f/jupyterlab/commands.py#L2078

I wonder whether this is because the `schemaDir` in `jupyterlab_widgets` starts with `./` here:

https://github.com/jupyter-widgets/ipywidgets/blob/6dff84d5fec69d95c860b3039024fc688cf0c413/python/jupyterlab_widgets/package.json#L95

Which would make the string comparison fail. For reference the cookiecutter does not seem to be using the leading `./`: https://github.com/jupyterlab/extension-cookiecutter-ts/blob/1657093417dd510665defd87006ef5a91ea4be5e/%7B%7Bcookiecutter.python_name%7D%7D/package.json#L89

**Comment by jtpio** [comment] 2021-11-10 10:41
FYI @jhamet93 https://github.com/jupyterlab/jupyterlab/pull/11427 should provide a fix for this, in case you would like to check it out.

**Closed** 2021-11-10 12:10 UTC
