### ISSUE TITLE
FileUpload cannot be imported

### ISSUE THREAD

**Issue by alex4200** [jupyter-widgets/ipywidgets#2822] opened 2020-03-18 13:23 UTC
Using the version 7.0.5 of ipywidgets I am unable to usen[FileUpload](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#File-Upload):

```
import ipywidgets as widgets
upload = widgets.FileUpload(description='Choose file')
```

Error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-8b54dcfb11d3> in <module>()
      1 import ipywidgets as widgets
----> 2 upload = widgets.FileUpload(description='Choose file')
      3 
      4 
      5 def upload_file(args):

AttributeError: module 'ipywidgets' has no attribute 'FileUpload'
```

Maybe I am missing something obvious?

**Comment by jasongrout** [comment] 2020-03-18 14:02
FileUpload is not in ipywidgets 7.0.5. Please upgrade to the latest 7.5.1 and you will be able to import it.

**Comment by alex4200** [comment] 2020-03-18 14:44
@jasongrout  Thanks for that info, but an upgrade might be impossible as this is not just for a single user, but for an architecture affecting potentially thousand of users. 

Is there any workaround to be able to upload a file within a jupyter notebook you are aware of, with or without the use of `ipywidgets` 7.0.5?

**Comment by jasongrout** [comment] 2020-03-18 17:32
Ah, I forgot the conversation we had in #2796 

From the discussion on https://github.com/jupyter-widgets/ipywidgets/issues/1542, you can see that previously there was a community widget, ipyupload (https://gitlab.com/oscar6echo/ipyupload) that may work for you.

**Comment by alex4200** [comment] 2020-03-19 13:21
Thanks for the link to `ipyupload`, but it does not seem to work. No widget or anything is shown in the notebook.

**Comment by jasongrout** [comment] 2020-03-19 13:34
> Thanks for the link to `ipyupload`, but it does not seem to work. No widget or anything is shown in the notebook.

Oh, it looks like it requires ipywidgets 7.4 or later: https://gitlab.com/oscar6echo/ipyupload/-/blob/master/requirements.txt#L1 (and the file history indicates even the first version has that requirement)

You might need to make a custom version of it that removes that requirement. Or if you are making a new widget package anyway, perhaps even better would be to copy the upload widget from ipywidgets 7.5 (or master, which has seen some improvements) as a new package?

**Comment by jasongrout** [comment] 2020-03-19 13:35
Actually, I guess that requirements.txt isn't a mandated requirement? Perhaps you just need to debug what the issue is, i.e., look at what errors you have in your javascript console, etc.

**Comment by jasongrout** [comment] 2020-03-19 13:37
ipywidgets 7.0.5 was released in November 2017, and 7.1 was released in December 2017. Just curious - what is the timeline for upgrades for your platform? Over two years without an upgrade is a pretty long time, so I'm curious what is considered normal for your platform.

**Comment by alex4200** [comment] 2020-03-19 14:03
I am not responsable for that platform, and I also think more often updates should be normal. \
But anyway, thanks a lot for the input so far, I will see what can be done.

**Comment by jasongrout** [comment] 2020-03-19 14:07
I'll close this as answered, then. Thanks.

**Closed by jasongrout** 2020-03-19 14:07 UTC

**Comment by alex4200** [comment] 2020-03-19 14:29
Just a followup question: I am not able to create a confined example with `ipywidgets` 7.5.1 to upload an image file and to display it. Following the documentation I tried the following piece of code


```
from IPython.display import display
from ipywidgets import widgets

def upload_file(args):
    upload_filename = list(args['new'].keys())[0]
    [uploaded_file] = w.value
    widgets.Image(value=uploaded_file["content"].tobytes())

w = widgets.FileUpload(
    accept='', # default
    multiple=False, # default
    disabled=False, # default
    style_button='darkblue' # default
   
)
display(w)
w.observe(upload_file, names=['value'])
```

But I got an error 

```
...
<ipython-input-15-cabfd8bf89b3> in upload_file(args)
      7     upload_filename = list(args['new'].keys())[0]
      8     [uploaded_file] = w.value
----> 9     widgets.Image(value=uploaded_file["content"].tobytes())
     10 
     11 w = widgets.FileUpload(

TypeError: string indices must be integers
```


What am I doing wrong? And what is that strange construct

`[a]=b` mean? I never seen that before.

**Comment by jasongrout** [comment] 2020-03-19 14:54
> `[a]=b` mean? I never seen that before.

It just unpacks the list one level. It's equivalent to `a = b[0]`.

**Comment by jasongrout** [comment] 2020-03-19 14:54
What version of python are you using?

**Comment by jasongrout** [comment] 2020-03-19 14:57
Ah, that error comes possibly because you are using the docs from master, but the widget from 7.5.1. Print out `args` to see what the structure of that value is, and you should see there how to access the file contents.

**Comment by alex4200** [comment] 2020-03-19 15:12
Thanks, maybe I fixed that error (I do not get an error anymore), but the png image is still not displayed:

```
from IPython.display import display
from ipywidgets import widgets

def upload_file(args):
    upload_filename = list(args['new'].keys())[0]
    uploaded_file = args['new'][upload_filename]
    widgets.Image(value=uploaded_file["content"])

w = widgets.FileUpload(
    accept='', # default
    multiple=False, # default
    disabled=False, # default
    style_button='darkblue' # default 
)
display(w)
w.observe(upload_file, names=['value'])
```

**Comment by jasongrout** [comment] 2020-03-19 15:16
Is the `uploaded_file["content"]` a binary buffer like Image expects? I'm not sure it is in 7.5.1.

**Comment by alex4200** [comment] 2020-03-19 15:17
I seem so; when printed I see

`b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\...`

**Comment by jasongrout** [comment] 2020-03-19 17:17
Wait. Where in there are you displaying the image widget? Shouldn't you create the image widget outside of the function, then just set the value inside the function?

**Comment by alex4200** [comment] 2020-03-20 07:03
Yes you are right! Now it works as expected. Thanks a lot!
