### ISSUE TITLE
ipywidgets-6.0.0.rc2 doesnt behave as expected in Sage.

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [jupyter-widgets/ipywidgets#1161] opened 2017-02-25 20:23 UTC
This is related to Sage's ticket [#21267](https://trac.sagemath.org/ticket/21267). The ticket's author ported pywidgets-6.0.0.rc2 and widgetsnbextension-2.0.0rc1 to Sage, and was able to create Sage "interacts" (i. e. interactive plots using Sage-compatible widgets) in a Jupyter notebook using Sage's kernel.

Trying to reproduce is results, I merged his tree in my Sage installation, with no errors. However, When trying to reproduce Sage documentation examples (see [here](http://doc.sagemath.org/html/en/prep/Quickstarts/Interact.html)), I obtained only static graphs reflecting the default values of the widgets, and no widgets at all.

Furthermore, tje following message was printed in the terminal window from which Sage was launched (Sage launches its browser itself) : 
```
[IPKernelApp] WARNING | The installed widget Javascript is the wrong version. It must satisfy the semver range ~2.1.0.
```

The ticket's author thinks that : 

> This is most likely not Sage-related, so please report this issue upstream to ipywidgets

Which I do. I tried to empty the caches of both Firefox and Chrimium, to no avail...

A (likely unrelated) information : Sages starts Firefox in order to display its worksheet, even when it is lainched with the "SAGE_BROWSER=chromium" environment variable ; this is abnormal...

HTH,

**Comment by jdemeyer** [comment] 2017-03-01 09:41
This is caused by having two installations of `ipywidgets`: one system-wide and one within Sage. Somehow `ipywidgets` does not pick up the "correct" version of the javascript in this case.

**Comment by jasongrout** [comment] 2017-03-17 20:16
Is this resolved?

This sounds like it may be a problem with the notebook extension mechanism, then - the extension mechanism is confusing and error-prone. It sounds like we should close this and note yet another reason to implement something like https://github.com/jupyter/notebook/issues/1706.

**Comment by jdemeyer** [comment] 2017-03-17 20:59
It's not resolved but I agree that it's not an ipywidgets issue.

The problem turned out to be conflicting installations of ipywidgets (one system-wide and one user install).

**Closed** 2017-04-08 03:26 UTC
