### ISSUE TITLE
conda install ipywidgets doesn't install the jupyter-js-widgets anymore

### ISSUE THREAD

**Issue by beenje** [jupyter-widgets/ipywidgets#1721] opened 2017-09-19 20:04 UTC
According to the [documentation](http://ipywidgets.readthedocs.io/en/stable/user_install.html#with-conda), running "conda install -c conda-forge ipywidgets" should install and enable the extension.
That's not the case with the latest release:

```
$ docker run --rm -it jupyter/minimal-notebook bash
jovyan@c3094235e935:~$ conda install --yes ipywidgets
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    ipywidgets:         7.0.1-py_2 conda-forge
    widgetsnbextension: 3.0.3-py_1 conda-forge

widgetsnbexten 100% |###########################################################################################| Time: 0:00:01 810.71 kB/s
ipywidgets-7.0 100% |###########################################################################################| Time: 0:00:00  24.18 MB/s
jovyan@c3094235e935:~$ jupyter nbextension list
Known nbextensions:
  config dir: /opt/conda/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: problems found:
        - require?  X jupyter-js-widgets/extension
jovyan@c3094235e935:~$ ls /opt/conda/share/jupyter/nbextensions
ls: cannot access '/opt/conda/share/jupyter/nbextensions': No such file or directory
jovyan@c3094235e935:~$ find /opt/conda -name jupyter-js-widgets
```
jupyter-js-widgets is not installed. I had to run:

```
jovyan@c3094235e935:~$ jupyter nbextension install --py widgetsnbextension --sys-prefix
Installing /opt/conda/lib/python3.6/site-packages/widgetsnbextension/static -> jupyter-js-widgets
Making directory: /opt/conda/share/jupyter/nbextensions/jupyter-js-widgets/
Copying: /opt/conda/lib/python3.6/site-packages/widgetsnbextension/static/extension.js -> /opt/conda/share/jupyter/nbextensions/jupyter-js-widgets/extension.js
Copying: /opt/conda/lib/python3.6/site-packages/widgetsnbextension/static/extension.js.map -> /opt/conda/share/jupyter/nbextensions/jupyter-js-widgets/extension.js.map
- Validating: OK

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable widgetsnbextension --py --sys-prefix

jovyan@c3094235e935:~$ find /opt/conda -name jupyter-js-widgets
/opt/conda/share/jupyter/nbextensions/jupyter-js-widgets
jovyan@c3094235e935:~$ ls /opt/conda/share/jupyter/nbextensions
jupyter-js-widgets
```

It was working fine with widgetsnbextension=3.0.2:

```
$ docker run --rm -it jupyter/minimal-notebook bash
jovyan@9803a2692ac4:~$ conda install --yes ipywidgets widgetsnbextension=3.0.2
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /opt/conda:

The following NEW packages will be INSTALLED:

    ipywidgets:         7.0.1-py_2   conda-forge
    widgetsnbextension: 3.0.2-py36_0 conda-forge

widgetsnbexten 100% |####################################################################################################| Time: 0:00:01   1.34 MB/s
ipywidgets-7.0 100% |####################################################################################################| Time: 0:00:00  24.51 MB/s
jovyan@9803a2692ac4:~$ jupyter nbextension list
Known nbextensions:
  config dir: /opt/conda/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
jovyan@9803a2692ac4:~$ ls /opt/conda/share/jupyter/nbextensions/
jupyter-js-widgets
```

It looks like a regression in widgetsnbextension 3.0.3

**Comment by jasongrout** [comment] 2017-09-19 23:08
We switched to noarch conda-forge packages in https://github.com/conda-forge/ipywidgets-feedstock/pull/27 and https://github.com/conda-forge/widgetsnbextension-feedstock/pull/29. I wonder if the switch made it so that the normal files aren't copied anymore?

If you install from pip in a clean environment, do you have to do the install step? If so, that points to the conda-forge package being the problem.

I'll be able to check on this in a few days too.

**Comment by npyoung** [comment] 2017-09-20 01:02
I just tried a fresh conda install and ran
```
conda install widgetsnbextension=3.0.2
conda install -c conda-forge ipywidgets=7.0.1
```
Widgets are still not working and I get a ` 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170919175641`. jupyter-js-widgets doesn't show up in my list of extensions. I'm not sure why it worked for @beenje but it's possible the regression occurred earlier.

**Comment by beenje** [comment] 2017-09-20 06:28
Install from pip with a clean environment works. No install step required:
```
$ docker run --rm -it jupyter/minimal-notebook bash
jovyan@08e89023a107:~/work$ pip install ipywidgets
Collecting ipywidgets
  Downloading ipywidgets-7.0.1-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 3.0MB/s
Requirement already satisfied (use --upgrade to upgrade): traitlets>=4.3.1 in /opt/conda/lib/python3.5/site-packages (from ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): nbformat>=4.2.0 in /opt/conda/lib/python3.5/site-packages (from ipywidgets)
Collecting widgetsnbextension~=3.0.0 (from ipywidgets)
  Downloading widgetsnbextension-3.0.3-py2.py3-none-any.whl (2.5MB)
    100% |████████████████████████████████| 2.5MB 449kB/s
Requirement already satisfied (use --upgrade to upgrade): ipython>=4.0.0; python_version >= "3.3" in /opt/conda/lib/python3.5/site-packages (from ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): ipykernel>=4.5.1 in /opt/conda/lib/python3.5/site-packages (from ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): decorator in /opt/conda/lib/python3.5/site-packages (from traitlets>=4.3.1->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /opt/conda/lib/python3.5/site-packages (from traitlets>=4.3.1->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): six in /opt/conda/lib/python3.5/site-packages (from traitlets>=4.3.1->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): jsonschema!=2.5.0,>=2.4 in /opt/conda/lib/python3.5/site-packages (from nbformat>=4.2.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): jupyter-core in /opt/conda/lib/python3.5/site-packages (from nbformat>=4.2.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): notebook>=4.4.1 in /opt/conda/lib/python3.5/site-packages (from widgetsnbextension~=3.0.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): prompt-toolkit<2.0.0,>=1.0.4 in /opt/conda/lib/python3.5/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): simplegeneric>0.8 in /opt/conda/lib/python3.5/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): pickleshare in /opt/conda/lib/python3.5/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): pygments in /opt/conda/lib/python3.5/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): jedi>=0.10 in /opt/conda/lib/python3.5/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=18.5 in /opt/conda/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): pexpect; sys_platform != "win32" in /opt/conda/lib/python3.5/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): jupyter-client in /opt/conda/lib/python3.5/site-packages (from ipykernel>=4.5.1->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.0 in /opt/conda/lib/python3.5/site-packages (from ipykernel>=4.5.1->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): terminado>=0.3.3; sys_platform != "win32" in /opt/conda/lib/python3.5/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.0.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /opt/conda/lib/python3.5/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.0.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): nbconvert in /opt/conda/lib/python3.5/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.0.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in /opt/conda/lib/python3.5/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0; python_version >= "3.3"->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): pyzmq>=13 in /opt/conda/lib/python3.5/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2.1 in /opt/conda/lib/python3.5/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.23 in /opt/conda/lib/python3.5/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.0.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): pandocfilters>=1.4.1 in /opt/conda/lib/python3.5/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.0.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): testpath in /opt/conda/lib/python3.5/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.0.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): entrypoints>=0.2.2 in /opt/conda/lib/python3.5/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.0.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): mistune!=0.6 in /opt/conda/lib/python3.5/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.0.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): bleach in /opt/conda/lib/python3.5/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.0.0->ipywidgets)
Requirement already satisfied (use --upgrade to upgrade): html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 in /opt/conda/lib/python3.5/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.0.0->ipywidgets)
Installing collected packages: widgetsnbextension, ipywidgets
Successfully installed ipywidgets-7.0.1 widgetsnbextension-3.0.3
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
jovyan@08e89023a107:~/work$ find /opt/conda -name jupyter-js-widgets
/opt/conda/share/jupyter/nbextensions/jupyter-js-widgets
jovyan@08e89023a107:~/work$ jupyter nbextension enable --py widgetsnbextension --sys-prefix
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
```

So yes, it looks like a conda-forge package issue.

**Comment by beenje** [comment] 2017-09-20 06:36
@npyoung you should also install widgetsnbextension from conda-forge. That will work:

```
conda install -c conda-forge widgetsnbextension=3.0.2
conda install -c conda-forge ipywidgets=7.0.1
```

In the docker image I used (jupyter/minimal-notebook), conda-forge has already been added to the list of channels.

**Comment by pbugnion** [comment] 2017-09-20 06:38
I just verified that, on a clean VM, `conda install -c conda-forge ipywidgets` does not copy the JS extension into the extensions folder. Manually running:

```
jupyter nbextension install --py widgetsnbextension --sys-prefix
```

after the installation does copy the JS extension, so ipywidgets works normally afterwards.

**Comment by jasongrout** [comment] 2017-09-20 13:49
Putting in the reference milestone since it seems likely that the real issue is to be fixed in the conda-forge feedstock.

**Comment by pbugnion** [comment] 2017-09-21 06:53
For reference, this is now fixed with [this PR](https://github.com/conda-forge/widgetsnbextension-feedstock/pull/30). I just successfully installed ipywidgets from conda-forge.

**Comment by jasongrout** [comment] 2017-09-22 15:30
Thanks!

**Closed by jasongrout** 2017-09-22 15:30 UTC
