### ISSUE TITLE
Recursion failure running tests on Jenkins

### ISSUE THREAD

**Issue by takluyver** [jupyter-widgets/ipywidgets#1064] opened 2017-01-30 15:28 UTC
On the `jack-of-none` build on Jenkins, which builds master of all our repos together, I see this test failure; it appears to recurse between accessing `.max` and `.min` traitlets until it crashes. Hopefully this is the relevant piece of the traceback:

```
Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 516, in get
    value = obj._trait_values[self.name]
KeyError: 'min'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 516, in get
    value = obj._trait_values[self.name]
KeyError: 'max'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/ipywidgets/widgets/tests/test_interaction.py", line 739, in test_state_schema
    s = IntSlider()
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/ipywidgets/widgets/widget_int.py", line 58, in __init__
    super(cls, self).__init__(**kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/ipywidgets/widgets/widget_int.py", line 95, in __init__
    super(_BoundedInt, self).__init__(**kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/ipywidgets/widgets/widget_int.py", line 76, in __init__
    super(_Int, self).__init__(**kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 202, in __init__
    self.open()
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 215, in open
    state, buffer_keys, buffers = self._split_state_buffers(self.get_state())
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/ipywidgets/widgets/widget.py", line 309, in get_state
    value = to_json(getattr(self, k), self)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 545, in __get__
    return self.get(obj, cls)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 524, in get
    value = self._validate(obj, default)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 582, in _validate
    value = self._cross_validate(obj, value)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 588, in _cross_validate
    value = obj._trait_validators[self.name](obj, proposal)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/traitlets/traitlets.py", line 907, in __call__
    return self.func(*args, **kwargs)
  File "/var/lib/jenkins/shiningpanda/jobs/92f5a430/virtualenvs/d41d8cd9/lib/python3.5/site-packages/ipywidgets/widgets/widget_int.py", line 119, in _validate_max
    if max < self.min:
...
```

[Build log](https://jenkins.jupyter.org/job/jack-of-none/487/console).

**Comment by minrk** [comment] 2017-01-30 15:33
I think this might be related to something @SylvainCorlay found recently.

**Comment by SylvainCorlay** [comment] 2017-01-30 16:08
Yeah, traitlets master breaks widgets. I have not looked into it yet.

**Comment by takluyver** [comment] 2017-02-03 15:48
I've commented out ipywidgets on Jenkins for now so that we can test the other things. Once this is fixed, remind me to re-enable it.

**Comment by jasongrout** [comment] 2017-04-26 23:10
Reassigning to Future, since it seems it is a traitlets issue?

**Comment by jasongrout** [comment] 2017-09-05 16:00
Closing as a dupe of #1423.

**Closed by jasongrout** 2017-09-05 16:00 UTC
