### ISSUE TITLE
deleting cell with widget works but leaves JS console error

### ISSUE THREAD

**Issue by scottdraves** [jupyter-widgets/ipywidgets#1389] opened 2017-05-24 23:00 UTC
with a fresh conda env and the following package versions:
```
widgetsnbextension: 2.0.0-py35_0
ipywidgets:         6.0.0-py35_0
notebook:           5.0.0-py35_0
```
if I create a Python 3 notebook and run a cell like this:
```
from ipywidgets import *
IntSlider()
```
and then delete the cell (i use the "x" key), it works but I get the following stack trace on the JS console:
```
events.js:33 Exception in event handler for delete.Cell Error: Widget not attached.
    at Function.detach (widget.js:682)
    at JupyterPhosphorWidget.Widget.dispose (widget.js:70)
    at JupyterPhosphorWidget.dispose (widget.js:666)
    at IntSliderView.DOMWidgetView.remove (widget.js:837)
    at WidgetArea.clear (widgetarea.js:156)
    at window._Events.clearWidgetArea (extension.js:70)
    at window._Events.dispatch (jquery.min.js:5)
    at window._Events.y.handle (jquery.min.js:5)
    at Object.trigger (jquery.min.js:5)
    at window._Events.<anonymous> (jquery.min.js:5) 
(2) ["delete.Cell", Object, callee: (...), Symbol(Symbol.iterator): function]
```

i tried in an old env i had with nb v4.2.1 and ipywidgets v4 and could not reproduce.

chrome 58 on mac.

**Comment by jasongrout** [comment] 2017-05-25 22:18
Thanks for reporting this.

**Comment by jasongrout** [comment] 2017-05-26 18:34
I couldn't reproduce this with notebook master-ish and ipywidgets master. We did change significantly how widgets were displayed in ipywidgets master. Can you see if you can reproduce it with ipywidgets master?

**Comment by jasongrout** [comment] 2017-06-22 14:30
Closing as fixed in master. Please reopen if you see this still as an issue in master. Thanks for reporting this!

**Closed by jasongrout** 2017-06-22 14:30 UTC
Labels: needs info
