### ISSUE TITLE
interact_manual and widget display

### ISSUE THREAD

**Issue by disimone** [jupyter-widgets/ipywidgets#1329] opened 2017-05-03 09:21 UTC
Hi,

I am trying to use interact_manual to create/display some widgets. When activated, interact_manual should just update the contents of the widgets.

I have tried different implementations, but in all of them, interact_manual redraws new versions of the widgets below the existing ones, instead of replacing the contents. Here is an example, where each set of tabs results from a subsequent click on the interact button.

![image](https://cloud.githubusercontent.com/assets/25104002/25654653/2ecbcd64-2ff2-11e7-93d3-157889745cf1.png)

I assume I am doing something wrong here. What is the proper way of creating/displaying/updating widgets with interactive_manual?

In general, how do I cleanup all exising widgets from an output cell before displaying new ones?

Thanks for your help,

Andrea.

**Comment by jasongrout** [comment] 2017-05-09 19:03
Thanks so much for posting a screenshot. Could you also paste the code so when filing issues like this so it is easy for us to reproduce it for ourselves?

**Comment by jasongrout** [comment] 2017-05-09 19:21
This appears to work in the 7.0 alpha. And in 7.0 alpha, you'd just need to clear the cell output, since widgets are now normal outputs like anything else.

**Comment by jasongrout** [comment] 2017-05-09 19:23
Closing as working in 7.0. If this doesn't work for you in 7.0 (like in the alpha that was released), can you please reopen it?

**Closed by jasongrout** 2017-05-09 19:23 UTC

**Comment by disimone** [comment] 2017-05-10 14:31
Hi Jason, thanks for testing this. For the record, I confirm that this works in 7a

**Comment by jasongrout** [comment] 2017-05-10 14:33
Great! We working hard on getting 7.0 out the door.
