### ISSUE TITLE
Dropdown widget attributes does not update with options assignment

### ISSUE THREAD

**Issue by BenjaPH** [jupyter-widgets/ipywidgets#1762] opened 2017-10-19 09:42 UTC
After the initial creation of a dropdown widget when i  assign a new set of options the view does not update.
I know this issue is the same as #536 that it's already closed, but in my case, the problem came up after a recent update of anaconda, before the code worked well,
I am working on Windows 10
anaconda 5.0.0
jupyter notebook 5.0.0
ipywidgets 7.0.0
traitlets 4.3.2

The code is,

```
# widget Dropdown
import ipywidgets as widgets
from IPython.display import display

OptDict={'XXX':0,'YYY':1}
wDd2=widgets.Dropdown(options=OptDict,value=0,disabled=False)
print(wDd2, id(wDd2),"\n")

with wDd2.hold_trait_notifications():
    OptDict['ZZZ']=9
    wDd2.options=OptDict
    wDd2.value=1
print(wDd2.options, id(wDd2.options))
print(wDd2._options_labels, wDd2._options_values)

display(wDd2)

```
and the output,

```
Dropdown(options={'XXX': 0, 'YYY': 1}, value=0) 2205788730032 

{'ZZZ': 9, 'XXX': 0, 'YYY': 1} 2205789360520
('XXX', 'YYY') (0, 1)
```
It seems that the Dropdown widgets atributes (_options_labels, _options_values) are not updated with the assigment of wDd2.options=OptDict.
Are there any other instructions that force the updating of these attributes? or it is possible to synchronize them automatically with any changes of the variable 'OptDict' assigned at the Dropdown constructor?

**Comment by pbugnion** [comment] 2017-10-19 11:26
Thanks for submitting this. 

A good rule with widgets is to never mutate the traitlet values themselves. In this case, the problem is that you are mutating `OptDict`, but the `id` of `OptDict` is still the same. As far as widgets are concerned, it's the *same* dictionary. Thus, when you re-assign it to `option`, there has been no change.

To make this work, you want to copy `OptDict` and assign that copy to your dropdown's `options` traitlet:

```py
import ipywidgets as widgets
from IPython.display import display

options = {'XXX':0,'YYY':1}
dropdown = widgets.Dropdown(options=options, value=0)

options_copy = options.copy()
options_copy['ZZZ'] = 9
dropdown.options = options_copy
print(dropdown._options_labels)
```

---

At some point, we are going to have eventful dictionaries and lists in traitlets, and this won't be a problem any more. Till then, you're probably best off treating traitlet values (i.e. the *things* assigned to traitlets, like `OptDict`) as immutable.

**Comment by BenjaPH** [comment] 2017-10-19 13:53
Thank you very much for your really fast answer and complete explanation.
This works fine, but now what i don't really understand is why the following code doesn't work,

```
import ipywidgets as widgets
from IPython.display import display

options = {'XXX':0,'YYY':1}
dropdown = widgets.Dropdown(options=options, value=0)

options['ZZZ'] = 9
print(dropdown.options, id(dropdown.options))
options_copy = options.copy()

dropdown.options = options_copy
print(dropdown.options, id(dropdown.options))
print(dropdown._options_labels)

```
I have just modified the sequence. First I append the additional option 'ZZZ' to the original dictionary and after copy it to a new one.
In this case, the object 'id' is also different and then the changes should be notified?

However, the output is wrong,
```
{'ZZZ': 9, 'YYY': 1, 'XXX': 0} 1563904903624
{'ZZZ': 9, 'YYY': 1, 'XXX': 0} 1563905022024
('YYY', 'XXX')
```
It could be related with your comment 'A good rule with widgets is to never mutate the traitlet values themselves' ??

**Comment by jasongrout** [comment] 2017-10-19 17:50
> First I append the additional option 'ZZZ' to the original dictionary and after copy it to a new one.

That's the issue. When you append the option to the original dictionary, that changes what the dropdown widget can see as its options. You make a copy and assign it, and the dropdown compares the copy with it's current dictionary, and sees no change.

We eliminated the dictionary from dropdown widgets in the runup to 7.0 to prevent exactly this kind of confusion, but put it back at several requests. I'm thinking now that we should look again at eliminating using a dictionary for the options object, and maybe make a convenience method that will set the options from a dictionary. Thoughts?

**Comment by BenjaPH** [comment] 2017-10-20 09:48
Ok, i think i have understood now the problem better. The solution that @pbugnion gave me completely solve my problem, but my confusion came up when i coded it in a slightly different order. Then, when the options set must be changed in any place of the code i will adopt the following pattern,
```
options_copy = dropdown.options.copy()    # obtain a copy of the object "different id" with the current options
options_copy['ZZZ'] = 9                                # add/modify new options
dropdown.options = options_copy               # reassign the updated new object
```
So the dropdown widget options assignment (new object id) trigger the observed value change event and internally pass the redundant check that the object contents are really different from the old one. Thus, modifies the _options_labels attribute.
i don't know if this reasoning is more or less correct but it works fine.
Thank you both for these great answers and please don't eliminate the dictionary for the options, this solution is a very easy workaround.

**Comment by jasongrout** [comment] 2017-10-20 15:50
> i don't know if this reasoning is more or less correct but it works fine.

That's exactly the case.

Closing as resolved, then.

**Closed by jasongrout** 2017-10-20 15:50 UTC
