### ISSUE TITLE
mathjax affects dropdown options inconsistently

### ISSUE THREAD

**Issue by mheilman** [jupyter-widgets/ipywidgets#1777] opened 2017-10-25 16:24 UTC
I noticed some strange behavior where dropdown options get rendered (I think) as equations by mathjax, but only when multiple dropdowns are displayed at the same time.

![screen shot 2017-10-25 at 11 13 53 am](https://user-images.githubusercontent.com/181744/32010031-43bce72c-b976-11e7-948d-8021025d1be2.png)

As a workaround, is there a way to disable MathJax for a single dropdown?

versions:

* notebook==5.1.0
* ipywidgets==7.0.3
* Python 3.6.2 :: Continuum Analytics, Inc.
* Chrome on MacOS

**Comment by mheilman** [comment] 2017-10-25 16:55
It looks like if `v` only has one `$` in it (e.g., `'$0 - 10'`), then mathjax doesn't ever get triggered.  (That's probably my workaround for now.)

**Comment by jasongrout** [comment] 2017-10-25 19:03
You can use `\$` to get a single dollar sign as well: `\$0 - \$10`.

**Comment by mheilman** [comment] 2017-10-25 19:12
Hmm... if I do `\$0 - \$10`, then I get the opposite behavior, but thanks, that might be a better workaround if I know there's gonna be multiple dropdowns.

![screen shot 2017-10-25 at 2 10 51 pm](https://user-images.githubusercontent.com/181744/32018083-5ece8cb0-b98e-11e7-9877-635416ceff28.png)

**Comment by jasongrout** [comment] 2017-10-25 19:13
I'm testing this - and I'm not getting mathjax rendering dropdown options (notebook 5.2, though). I'm checking notebook 5.1 right now.

**Comment by jasongrout** [comment] 2017-10-25 19:16
Never mind, I just reproduced the issue.

**Comment by jasongrout** [comment] 2017-10-25 19:18
I think it has to do with the `display` call, and `display` triggering a math rendering run. With the original code, either `HBox([d,d])` or `display(HBox([d,d]))` works for me.

**Comment by mheilman** [comment] 2017-10-25 19:21
Interesting.  Are you on notebook 5.2?  Putting the dropdowns in an HBox doesn't seem to solve it for me.

![screen shot 2017-10-25 at 2 20 22 pm](https://user-images.githubusercontent.com/181744/32018493-ac659aa8-b98f-11e7-8341-5acbffa5e3a8.png)

**Comment by jasongrout** [comment] 2017-10-25 19:27
I tried that in notebook 5.1.0:

```
conda create -n delete-1777 notebook=5.1 ipywidgets
source activate delete-1777
ipython kernel install --name delete_1777 --sys-prefix
```

**Comment by jasongrout** [comment] 2017-10-25 19:33
I just checked JupyterLab, and it doesn't have a problem at all.

**Comment by jasongrout** [comment] 2017-10-25 19:47
Definitely something weird going on. With the above environment setup, here's what I get:
![screen shot 2017-10-25 at 12 47 06 pm](https://user-images.githubusercontent.com/192614/32019628-b30ce6e8-b982-11e7-9b2f-9ee3d98c81bf.png)

**Comment by mheilman** [comment] 2017-10-25 20:46
fwiw, this doesn't seem to affect `ipywidgets.Label`

**Comment by jasongrout** [comment] 2017-10-25 21:38
I think this may be a bug in the notebook display logic. For example, see https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/outputarea.js#L651 - you'll notice that the code just checks to see if there is an html mimetype in the message, and if so, it appears to typeset the entire output area. In contrast, the JupyterLab implementation explicitly just typesets the specific output if needed (IIRC), not the entire output area.

**Comment by mheilman** [comment] 2017-10-25 21:44
Ah, nice find.

probably related: https://github.com/jupyter/notebook/issues/2444

**Comment by jasongrout** [comment] 2017-10-25 22:05
I just traced this down in the Chrome debugger to the issue in the notebook. Let's track this at the notebook issue, where the real problem is.

Note that we probably didn't trigger this until https://github.com/jupyter-widgets/ipywidgets/pull/1674, when we added an html mimetype to the widget display messages so we could have links to the documentation. It may make sense for us to roll back the https://github.com/jupyter-widgets/ipywidgets/pull/1674 because of this notebook bug.

The purpose in having an html mimetype in the display message was so that one message could show up in a notebook, while a different message could show up in the terminal.

**Comment by jasongrout** [comment] 2017-10-26 16:46
@ssanderson - given the above (breaking things in the current notebook because of a bug in the current notebook), what do you think of reverting #1674 so that we don't have an html error message anymore?

**Comment by jasongrout** [comment] 2017-10-27 16:33
Moving to 7.x - I think we'll really need to change the html error message to work around this bug.

**Comment by ssanderson** [comment] 2017-10-27 16:38
@jasongrout is there somewhere else we can put that error message that will still be visible without causing this bug (e.g., in the regular text repr)?

**Comment by jasongrout** [comment] 2017-10-27 16:41
The text mimetype is already being used for a very simple rendering. We could probably put a small message there if we needed to.

**Comment by jasongrout** [comment] 2018-03-20 17:51
The notebook issue is at https://github.com/jupyter/notebook/issues/2980.

**Closed** 2018-03-23 21:40 UTC
Labels: good first issue
