### ISSUE TITLE
select.unobserve(func) does not unobserve if names is specificed in select.observe

### ISSUE THREAD

**Issue by thomasaarholt** [jupyter-widgets/ipywidgets#2057] opened 2018-04-25 08:41 UTC
Sorry for awkward title.

In short, I expect `select.unobserve(func, names=traitlets.All)` to unobserve all names fed to the observer. However, the above does not unobserve `select.observe(func, names='value')`.

MWE:
```python
import ipywidgets as widgets

def add(value):
    select.options = select.options + (1,)
    
select = widgets.Select(options=('Cheese', 'Onions'), rows=15, value=None)
select2 = widgets.Select(options=('CLICK ME', 'OR ME'), rows=15, value=None)
select2.observe(add, names='value') # name is specified
select2.unobserve(add) # does not work
#select2.unobserve(add, names='value') #works

widgets.HBox([select, select2])
```

**Comment by jasongrout** [comment] 2018-04-25 14:53
Thanks! Can you move this issue to the traitlets repo? Here is the code for the unobserve function: https://github.com/ipython/traitlets/blob/b775646dee20c561147dac4794bd6bb2244696fd/traitlets/traitlets.py#L1338-L1357

**Comment by jasongrout** [comment] 2018-04-25 14:57
Looking at the code, it looks like traitlets.All is treated as a special name, rather than as a wildcard, i.e., it works as designed, even if it's not completely intuitive.

**Comment by thomasaarholt** [comment] 2018-04-25 15:40
That seems really odd to me.

From the [docs of `.observe`](http://traitlets.readthedocs.io/en/stable/api.html#traitlets.HasTraits.observe): 

> If names is All, the handler will apply to all traits. If a list of str, handler will apply to all names in the list. If a str, the handler will apply just to that name.

Shouldn't it then follow that the opposite is true? If you think that the current behaviour sounds strange, I'll make a issue at traitlets.

**Comment by jasongrout** [comment] 2018-04-25 15:49
I agree that the docs could be more descriptive of the behavior. There is a special name, All, which is not replaced with all of the trait names, but instead is its own special category for names. In other words, `observe(handler, names=All)` is different from `observe(handler, names=['every', 'traitlet', 'in', 'class'])`.

I would go ahead and open an issue there, even just pointing to this discussion, so the issue is raised. My guess is that it will lead to improved documentation.

**Comment by thomasaarholt** [comment] 2018-04-25 15:55
I'm all for that. I'll close this once I've got the discussion started in the other repo.

**Comment by codingS3b** [comment] 2018-09-27 15:11
Having a similar issue here. Has there been a workaround/solution to allow unregistering a callback function registered via `select2.observe(add, names='value')`?

**Comment by jasongrout** [comment] 2018-09-27 19:34
Closing since the traitlets issue is now open for discussion. Thanks again for bringing this up!

**Closed by jasongrout** 2018-09-27 19:34 UTC

**Comment by thomasaarholt** [comment] 2018-09-27 19:40
Great! Sorry I forgot to close this. Which is the trailets discussion issue?

**Comment by jasongrout** [comment] 2018-09-27 19:43
The issue you opened: https://github.com/ipython/traitlets/issues/485

**Comment by thomasaarholt** [comment] 2018-09-27 19:51
_coughs and sputters_
